// Admin Dashboard Components
export { default as Sidebar } from './Sidebar';
export { default as Header } from './Header';
export { default as StatsCard } from './StatsCard';
export { default as DashboardOverview } from './DashboardOverview';
export { default as UserManagementPage } from './UserManagementPage';
export { default as CourseManagementPage } from './CourseManagementPage';
export { default as DepartmentManagementPage } from './DepartmentManagementPage';
export { default as AcademicCalendarPage } from './AcademicCalendarPage';
export { default as AnalyticsReportsPage } from './AnalyticsReportsPage';
export { default as CommunicationPage } from './CommunicationPage';
export { default as FeedbackSupportPage } from './FeedbackSupportPage';
export { default as SystemConfigPage } from './SystemConfigPage';
export { default as ScheduleManagementPage } from './ScheduleManagementPage';
export { default as ExamSchedulePage } from './ExamSchedulePage';
export { default as EnrollmentPeriodPage } from './EnrollmentPeriodPage';
export { default as PrerequisitesManagementPage } from './PrerequisitesManagementPage';
export { StaffAssignmentPage } from './StaffAssignmentPage';
export { AttendanceManagementPage } from './AttendanceManagementPage';
export { RoleManagementPage } from './RoleManagementPage';
export { BackupCenterPage } from './BackupCenterPage';
export { PaymentManagementPage } from './PaymentManagementPage';
export { SecurityLogsPage } from './SecurityLogsPage';
export { SettingsHubPage } from './SettingsHubPage';
export { AdminNotificationsPage } from './AdminNotificationsPage';
export { AIInsightsPage } from './AIInsightsPage';
export { GlobalSearchPage } from './GlobalSearchPage';
