import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    search: 'Search...',
    notifications: 'Notifications',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    viewProfile: 'View Profile',
    logout: 'Logout',
    dashboard: 'Dashboard',
    itAdminDashboard: 'IT Admin Dashboard',
    systemConfig: 'System Configuration',
    integrations: 'Integrations & APIs',
    database: 'Database Management',
    monitoring: 'Monitoring & Performance',
    security: 'Security Management',
    aiManagement: 'AI Management',
    multiCampus: 'Multi-Campus',
    serverHealth: 'Server Health',
    apiStatus: 'API Status',
    uptime: 'Uptime',
    responseTime: 'Response Time',
    errorRate: 'Error Rate',
    activeConnections: 'Active Connections',
    cpuUsage: 'CPU Usage',
    memoryUsage: 'Memory Usage',
    diskSpace: 'Disk Space',
    networkTraffic: 'Network Traffic',
    backupStatus: 'Backup Status',
    lastBackup: 'Last Backup',
    nextBackup: 'Next Backup',
    runBackup: 'Run Backup Now',
    restoreBackup: 'Restore Backup',
    sslCertificates: 'SSL Certificates',
    accessLogs: 'Access Logs',
    securityEvents: 'Security Events',
    firewallRules: 'Firewall Rules',
    rateLimiting: 'Rate Limiting',
    sessionManagement: 'Session Management',
    aiModels: 'AI Models',
    aiUsage: 'AI Usage Statistics',
    aiCosts: 'AI Costs',
    campusSettings: 'Campus Settings',
    domainSettings: 'Domain Settings',
    brandingSettings: 'Branding Settings',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    close: 'Close',
    confirm: 'Confirm',
    actions: 'Actions',
    status: 'Status',
    healthy: 'Healthy',
    warning: 'Warning',
    critical: 'Critical',
    active: 'Active',
    inactive: 'Inactive',
    enabled: 'Enabled',
    disabled: 'Disabled',
    configure: 'Configure',
    viewDetails: 'View Details',
    refresh: 'Refresh',
    export: 'Export',
    // Dashboard Overview
    itInfrastructureDashboard: 'IT Infrastructure Dashboard',
    monitorServersDescription: 'Monitor servers, APIs, and system performance in real-time',
    serverStatus: 'Server Status',
    viewAll: 'View All',
    viewLogs: 'View Logs',
    recentItActivity: 'Recent IT Activity',
    quickActions: 'Quick Actions',
    checkApis: 'Check APIs',
    // System Configuration
    systemConfigDescription: 'Configure system settings, security policies, and branding',
    saveChanges: 'Save Changes',
    generalSettings: 'General Settings',
    securityPolicies: 'Security Policies',
    brandingAndDomain: 'Branding & Domain',
    maintenanceMode: 'Maintenance Mode',
    maintenanceModeDescription: 'Temporarily disable access to the platform',
    debugMode: 'Debug Mode',
    debugModeDescription: 'Enable detailed error logging',
    rateLimitPerMinute: 'Rate Limit (requests per minute)',
    maxFileUploadSize: 'Max File Upload Size (MB)',
    twoFactorAuth: 'Two-Factor Authentication',
    twoFactorAuthDescription: 'Require 2FA for all users',
    maxLoginAttempts: 'Max Login Attempts',
    passwordExpiry: 'Password Expiry (days)',
    companyName: 'Company Name',
    supportEmail: 'Support Email',
    primaryColor: 'Primary Color',
    secondaryColor: 'Secondary Color',
    sessionTimeout: 'Session Timeout (minutes)',
    sessionTimeoutDescription: 'Users will be logged out after this period of inactivity',
    activeSessionsOverview: 'Active Sessions Overview',
    activeNow: 'Active Now',
    today: 'Today',
    thisWeek: 'This Week',
    settingsSavedSuccess: 'Settings saved successfully!',
    // Integrations & APIs
    integrationsDescription: 'Manage external service integrations and API configurations',
    activeIntegrations: 'Active Integrations',
    totalApiCallsToday: 'Total API Calls Today',
    monthlyCost: 'Monthly Cost',
    configuredIntegrations: 'Configured Integrations',
    type: 'Type',
    enterNewApiKey: 'Enter new API key',
    usage: 'Usage',
    sync: 'Sync',
    // Database Management
    databaseDescription: 'Manage database backups, restores, and retention policies',
    databaseSize: 'Database Size',
    backupStorage: 'Backup Storage',
    recoveryPoint: 'Recovery Point',
    runManualBackup: 'Run Manual Backup',
    backupType: 'Backup Type',
    fullBackup: 'Full Backup',
    incrementalBackup: 'Incremental Backup',
    differentialBackup: 'Differential Backup',
    backupScheduleHistory: 'Backup Schedule & History',
    backupName: 'Backup Name',
    schedule: 'Schedule',
    lastRun: 'Last Run',
    size: 'Size',
    retention: 'Retention',
    download: 'Download',
    restore: 'Restore',
    // Monitoring & Performance
    monitoringDescription: 'Monitor server health, API performance, and system metrics',
    avgResponseTime: 'Avg Response Time',
    requestThroughput: 'Request Throughput',
    fromLastHour: 'from last hour',
    cpu: 'CPU',
    memory: 'Memory',
    restart: 'Restart',
    performanceTrends24h: 'Performance Trends (24h)',
    performanceChartsPlaceholder: 'Performance charts will be displayed here',
    integrateChartingLibrary: 'Integrate with a charting library like Recharts',
    // Security Management
    securityDescription: 'Monitor security events, manage certificates, and view access logs',
    exportLogs: 'Export Logs',
    securityScore: 'Security Score',
    activeAlerts: 'Active Alerts',
    failedLogins24h: 'Failed Logins (24h)',
    activeCertificates: 'Active Certificates',
    domain: 'Domain',
    issuer: 'Issuer',
    validFrom: 'Valid From',
    validTo: 'Valid To',
    renew: 'Renew',
    high: 'high',
    medium: 'medium',
    low: 'low',
    valid: 'valid',
    expiring: 'expiring',
    expired: 'expired',
    // AI Management
    aiManagementDescription: 'Manage AI model settings, monitor usage, and optimize costs',
    activeModels: 'Active Models',
    totalRequests: 'Total Requests',
    avgCostPerRequest: 'Avg Cost/Request',
    aiModelsConfig: 'AI Models Configuration',
    purpose: 'Purpose',
    costPerRequest: 'Cost per Request',
    monthlyUsage: 'Monthly Usage',
    requests: 'requests',
    settings: 'Settings',
    aiUsageTrends: 'AI Usage Trends',
    aiUsageAnalyticsPlaceholder: 'AI usage analytics will be displayed here',
    // Multi-Campus
    multiCampusManagement: 'Multi-Campus Management',
    multiCampusDescription: 'Manage multiple campus configurations and settings',
    addCampus: 'Add Campus',
    totalCampuses: 'Total Campuses',
    totalStudents: 'Total Students',
    totalInstructors: 'Total Instructors',
    totalStorage: 'Total Storage',
    campusOverview: 'Campus Overview',
    students: 'Students',
    instructors: 'Instructors',
    storage: 'Storage',
    maintenance: 'maintenance',
    // Shared status values
    completed: 'completed',
    running: 'running',
    failed: 'failed',
  },
  ar: {
    search: 'بحث...',
    notifications: 'الإشعارات',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    viewProfile: 'عرض الملف الشخصي',
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    itAdminDashboard: 'لوحة تحكم مدير تقنية المعلومات',
    systemConfig: 'إعدادات النظام',
    integrations: 'التكاملات و APIs',
    database: 'إدارة قواعد البيانات',
    monitoring: 'المراقبة والأداء',
    security: 'إدارة الأمان',
    aiManagement: 'إدارة الذكاء الاصطناعي',
    multiCampus: 'متعدد الحرم الجامعي',
    serverHealth: 'صحة الخادم',
    apiStatus: 'حالة API',
    uptime: 'وقت التشغيل',
    responseTime: 'وقت الاستجابة',
    errorRate: 'معدل الأخطاء',
    activeConnections: 'الاتصالات النشطة',
    cpuUsage: 'استخدام المعالج',
    memoryUsage: 'استخدام الذاكرة',
    diskSpace: 'مساحة القرص',
    networkTraffic: 'حركة الشبكة',
    backupStatus: 'حالة النسخ الاحتياطي',
    lastBackup: 'آخر نسخة احتياطية',
    nextBackup: 'النسخة الاحتياطية التالية',
    runBackup: 'تشغيل نسخة احتياطية الآن',
    restoreBackup: 'استعادة نسخة احتياطية',
    sslCertificates: 'شهادات SSL',
    accessLogs: 'سجلات الوصول',
    securityEvents: 'الأحداث الأمنية',
    firewallRules: 'قواعد جدار الحماية',
    rateLimiting: 'تحديد المعدل',
    sessionManagement: 'إدارة الجلسات',
    aiModels: 'نماذج الذكاء الاصطناعي',
    aiUsage: 'إحصائيات استخدام الذكاء الاصطناعي',
    aiCosts: 'تكاليف الذكاء الاصطناعي',
    campusSettings: 'إعدادات الحرم الجامعي',
    domainSettings: 'إعدادات النطاق',
    brandingSettings: 'إعدادات العلامة التجارية',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجاح',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    close: 'إغلاق',
    confirm: 'تأكيد',
    actions: 'الإجراءات',
    status: 'الحالة',
    healthy: 'سليم',
    warning: 'تحذير',
    critical: 'حرج',
    active: 'نشط',
    inactive: 'غير نشط',
    enabled: 'مفعل',
    disabled: 'معطل',
    configure: 'تكوين',
    viewDetails: 'عرض التفاصيل',
    refresh: 'تحديث',
    export: 'تصدير',
    // Dashboard Overview
    itInfrastructureDashboard: 'لوحة تحكم البنية التحتية لتقنية المعلومات',
    monitorServersDescription: 'مراقبة الخوادم و APIs وأداء النظام في الوقت الفعلي',
    serverStatus: 'حالة الخادم',
    viewAll: 'عرض الكل',
    viewLogs: 'عرض السجلات',
    recentItActivity: 'نشاط تقنية المعلومات الأخير',
    quickActions: 'إجراءات سريعة',
    checkApis: 'فحص APIs',
    // System Configuration
    systemConfigDescription: 'تكوين إعدادات النظام وسياسات الأمان والعلامة التجارية',
    saveChanges: 'حفظ التغييرات',
    generalSettings: 'الإعدادات العامة',
    securityPolicies: 'سياسات الأمان',
    brandingAndDomain: 'العلامة التجارية والنطاق',
    maintenanceMode: 'وضع الصيانة',
    maintenanceModeDescription: 'تعطيل الوصول إلى المنصة مؤقتاً',
    debugMode: 'وضع التصحيح',
    debugModeDescription: 'تفعيل تسجيل الأخطاء التفصيلي',
    rateLimitPerMinute: 'حد المعدل (طلبات في الدقيقة)',
    maxFileUploadSize: 'الحد الأقصى لحجم رفع الملفات (ميجابايت)',
    twoFactorAuth: 'المصادقة الثنائية',
    twoFactorAuthDescription: 'طلب المصادقة الثنائية لجميع المستخدمين',
    maxLoginAttempts: 'الحد الأقصى لمحاولات تسجيل الدخول',
    passwordExpiry: 'انتهاء صلاحية كلمة المرور (أيام)',
    companyName: 'اسم الشركة',
    supportEmail: 'بريد الدعم الإلكتروني',
    primaryColor: 'اللون الأساسي',
    secondaryColor: 'اللون الثانوي',
    sessionTimeout: 'مهلة الجلسة (دقائق)',
    sessionTimeoutDescription: 'سيتم تسجيل خروج المستخدمين بعد فترة عدم النشاط هذه',
    activeSessionsOverview: 'نظرة عامة على الجلسات النشطة',
    activeNow: 'نشط الآن',
    today: 'اليوم',
    thisWeek: 'هذا الأسبوع',
    settingsSavedSuccess: 'تم حفظ الإعدادات بنجاح!',
    // Integrations & APIs
    integrationsDescription: 'إدارة تكاملات الخدمات الخارجية وتكوينات API',
    activeIntegrations: 'التكاملات النشطة',
    totalApiCallsToday: 'إجمالي استدعاءات API اليوم',
    monthlyCost: 'التكلفة الشهرية',
    configuredIntegrations: 'التكاملات المكوّنة',
    type: 'النوع',
    enterNewApiKey: 'أدخل مفتاح API الجديد',
    usage: 'الاستخدام',
    sync: 'مزامنة',
    // Database Management
    databaseDescription: 'إدارة النسخ الاحتياطي لقاعدة البيانات والاستعادة وسياسات الاحتفاظ',
    databaseSize: 'حجم قاعدة البيانات',
    backupStorage: 'تخزين النسخ الاحتياطي',
    recoveryPoint: 'نقطة الاستعادة',
    runManualBackup: 'تشغيل نسخة احتياطية يدوية',
    backupType: 'نوع النسخ الاحتياطي',
    fullBackup: 'نسخة احتياطية كاملة',
    incrementalBackup: 'نسخة احتياطية تزايدية',
    differentialBackup: 'نسخة احتياطية تفاضلية',
    backupScheduleHistory: 'جدول النسخ الاحتياطي والسجل',
    backupName: 'اسم النسخة الاحتياطية',
    schedule: 'الجدول',
    lastRun: 'آخر تشغيل',
    size: 'الحجم',
    retention: 'الاحتفاظ',
    download: 'تنزيل',
    restore: 'استعادة',
    // Monitoring & Performance
    monitoringDescription: 'مراقبة صحة الخادم وأداء API ومقاييس النظام',
    avgResponseTime: 'متوسط وقت الاستجابة',
    requestThroughput: 'معدل الطلبات',
    fromLastHour: 'من الساعة الماضية',
    cpu: 'المعالج',
    memory: 'الذاكرة',
    restart: 'إعادة تشغيل',
    performanceTrends24h: 'اتجاهات الأداء (24 ساعة)',
    performanceChartsPlaceholder: 'سيتم عرض مخططات الأداء هنا',
    integrateChartingLibrary: 'التكامل مع مكتبة رسوم بيانية مثل Recharts',
    // Security Management
    securityDescription: 'مراقبة الأحداث الأمنية وإدارة الشهادات وعرض سجلات الوصول',
    exportLogs: 'تصدير السجلات',
    securityScore: 'نقاط الأمان',
    activeAlerts: 'التنبيهات النشطة',
    failedLogins24h: 'تسجيلات الدخول الفاشلة (24 ساعة)',
    activeCertificates: 'الشهادات النشطة',
    domain: 'النطاق',
    issuer: 'الجهة المصدرة',
    validFrom: 'صالح من',
    validTo: 'صالح حتى',
    renew: 'تجديد',
    high: 'مرتفع',
    medium: 'متوسط',
    low: 'منخفض',
    valid: 'صالح',
    expiring: 'قيد الانتهاء',
    expired: 'منتهي',
    // AI Management
    aiManagementDescription:
      'إدارة إعدادات نماذج الذكاء الاصطناعي ومراقبة الاستخدام وتحسين التكاليف',
    activeModels: 'النماذج النشطة',
    totalRequests: 'إجمالي الطلبات',
    avgCostPerRequest: 'متوسط التكلفة/الطلب',
    aiModelsConfig: 'تكوين نماذج الذكاء الاصطناعي',
    purpose: 'الغرض',
    costPerRequest: 'التكلفة لكل طلب',
    monthlyUsage: 'الاستخدام الشهري',
    requests: 'طلبات',
    settings: 'الإعدادات',
    aiUsageTrends: 'اتجاهات استخدام الذكاء الاصطناعي',
    aiUsageAnalyticsPlaceholder: 'سيتم عرض تحليلات استخدام الذكاء الاصطناعي هنا',
    // Multi-Campus
    multiCampusManagement: 'إدارة متعدد الحرم الجامعي',
    multiCampusDescription: 'إدارة تكوينات وإعدادات الحرم الجامعي المتعدد',
    addCampus: 'إضافة حرم جامعي',
    totalCampuses: 'إجمالي الحرم الجامعي',
    totalStudents: 'إجمالي الطلاب',
    totalInstructors: 'إجمالي المدرسين',
    totalStorage: 'إجمالي التخزين',
    campusOverview: 'نظرة عامة على الحرم الجامعي',
    students: 'الطلاب',
    instructors: 'المدرسين',
    storage: 'التخزين',
    maintenance: 'صيانة',
    // Shared status values
    completed: 'مكتمل',
    running: 'قيد التشغيل',
    failed: 'فشل',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('eduverse-language');
      return (saved as Language) || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('eduverse-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
