import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

// Comprehensive translations for the instructor dashboard
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    search: 'Search...',
    searchPlaceholder: 'Search Courses, Students, Materials...',
    notifications: 'Notifications',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    viewProfile: 'View Profile',
    logout: 'Logout',

    // Sidebar
    dashboard: 'Dashboard',
    courses: 'Courses',
    students: 'Students',
    attendance: 'Attendance',
    analytics: 'Analytics',
    communication: 'Communication',
    aiTools: 'AI Tools',
    settings: 'Settings',
    calendar: 'Calendar',
    grading: 'Grading',

    // Dashboard Overview
    welcomeBack: 'Welcome back',
    instructorDashboard: 'Instructor Dashboard',
    overviewDescription:
      'Manage your courses, track student performance, and access AI teaching tools.',
    todaySchedule: "Today's Schedule",
    upcomingDeadlines: 'Upcoming Deadlines',
    quickStats: 'Quick Stats',
    recentActivity: 'Recent Activity',

    // Stats
    totalStudents: 'Total Students',
    activeCourses: 'Active Courses',
    avgAttendance: 'Avg Attendance',
    pendingGrading: 'Pending Grading',
    assignmentsToGrade: 'Assignments to Grade',

    // Courses
    myCourses: 'My Courses',
    createCourse: 'Create Course',
    courseManagement: 'Course Management',
    courseCode: 'Course Code',
    courseName: 'Course Name',
    semester: 'Semester',
    credits: 'Credits',
    enrolled: 'Enrolled',
    capacity: 'Capacity',
    schedule: 'Schedule',
    room: 'Room',
    status: 'Status',
    active: 'Active',
    archived: 'Archived',
    viewCourse: 'View Course',
    editCourse: 'Edit Course',
    archiveCourse: 'Archive Course',
    courseDetails: 'Course Details',
    courseMaterials: 'Course Materials',
    courseSettings: 'Course Settings',

    // Students
    studentRoster: 'Student Roster',
    allStudents: 'All Students',
    studentName: 'Student Name',
    studentId: 'Student ID',
    email: 'Email',
    grade: 'Grade',
    attendanceRate: 'Attendance Rate',
    performance: 'Performance',
    contactStudent: 'Contact Student',
    viewProfile: 'View Profile',
    atRisk: 'At Risk',
    onTrack: 'On Track',
    excellent: 'Excellent',

    // Attendance
    attendanceManagement: 'Attendance Management',
    takeAttendance: 'Take Attendance',
    attendanceHistory: 'Attendance History',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    excused: 'Excused',
    markAttendance: 'Mark Attendance',
    aiAttendance: 'AI Attendance',
    uploadPhoto: 'Upload Photo',
    detectStudents: 'Detect Students',
    confirmAttendance: 'Confirm Attendance',
    attendanceRecords: 'Attendance Records',
    overallAttendance: 'Overall Attendance',
    lowAttendanceWarning: 'Low Attendance Warning',

    // Analytics
    courseAnalytics: 'Course Analytics',
    studentPerformance: 'Student Performance',
    gradeDistribution: 'Grade Distribution',
    attendanceTrends: 'Attendance Trends',
    topicsMastery: 'Topics Mastery',
    atRiskStudents: 'At-Risk Students',
    performanceTrends: 'Performance Trends',
    exportReport: 'Export Report',
    generateReport: 'Generate Report',
    weeklyReport: 'Weekly Report',
    monthlyReport: 'Monthly Report',
    semesterReport: 'Semester Report',
    averageGrade: 'Average Grade',
    completionRate: 'Completion Rate',
    engagementScore: 'Engagement Score',

    // Communication
    communicationCenter: 'Communication Center',
    announcements: 'Announcements',
    createAnnouncement: 'Create Announcement',
    scheduleAnnouncement: 'Schedule Announcement',
    sendNow: 'Send Now',
    scheduleFor: 'Schedule For',
    announcementTitle: 'Title',
    announcementContent: 'Content',
    selectCourses: 'Select Courses',
    allCourses: 'All Courses',
    directMessages: 'Direct Messages',
    courseChats: 'Course Chats',
    sendMessage: 'Send Message',
    typeMessage: 'Type a Message...',
    messageStudents: 'Message Students',
    messageTA: 'Message TA',

    // AI Tools
    aiTeachingTools: 'AI Teaching Tools',
    aiPowered: 'AI-Powered',
    generateQuiz: 'Generate Quiz',
    generateQuestions: 'Generate Questions',
    autoGrading: 'Auto Grading',
    contentSummarizer: 'Content Summarizer',
    lectureAssistant: 'Lecture Assistant',
    smartRecommendations: 'Smart Recommendations',
    voiceToText: 'Voice to Text',
    imageToText: 'Image to Text',
    aiChatbot: 'AI Chatbot',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    numberOfQuestions: 'Number of Questions',
    questionType: 'Question Type',
    multipleChoice: 'Multiple Choice',
    trueFalse: 'True/False',
    shortAnswer: 'Short Answer',
    essay: 'Essay',
    generateFromContent: 'Generate from Content',
    uploadContent: 'Upload Content',
    pasteContent: 'Paste Content',
    evyAssistant: 'Evy AI Assistant',

    // Grading
    gradingCenter: 'Grading Center',
    pendingSubmissions: 'Pending Submissions',
    gradedSubmissions: 'Graded Submissions',
    autoGrade: 'Auto Grade',
    manualGrade: 'Manual Grade',
    provideFeedback: 'Provide Feedback',
    submitGrade: 'Submit Grade',
    batchGrade: 'Batch Grade',
    rubric: 'Rubric',
    createRubric: 'Create Rubric',
    applyRubric: 'Apply Rubric',
    score: 'Score',
    maxScore: 'Max Score',
    feedback: 'Feedback',
    aiSuggestion: 'AI Suggestion',

    // Assignments
    assignments: 'Assignments',
    createAssignment: 'Create Assignment',
    assignmentTitle: 'Assignment Title',
    description: 'Description',
    dueDate: 'Due Date',
    points: 'Points',
    attachments: 'Attachments',
    submissions: 'Submissions',
    notSubmitted: 'Not Submitted',
    submitted: 'Submitted',
    graded: 'Graded',
    lateSubmissions: 'Late Submissions',
    allowLate: 'Allow Late Submissions',
    latePenalty: 'Late Penalty',

    // Calendar & Schedule
    academicCalendar: 'Academic Calendar',
    examSchedule: 'Exam Schedule',
    officeHours: 'Office Hours',
    setOfficeHours: 'Set Office Hours',
    classSchedule: 'Class Schedule',
    addEvent: 'Add Event',
    eventTitle: 'Event Title',
    eventDate: 'Event Date',
    eventTime: 'Event Time',
    eventLocation: 'Location',
    recurringEvent: 'Recurring Event',

    // Registration & Settings
    registrationPeriod: 'Registration Period',
    courseCapacity: 'Course Capacity',
    waitlist: 'Waitlist',
    enableWaitlist: 'Enable Waitlist',
    waitlistCapacity: 'Waitlist Capacity',
    prerequisites: 'Prerequisites',
    courseFeatures: 'Course Features',
    enableFeature: 'Enable',
    disableFeature: 'Disable',
    taCollaboration: 'TA Collaboration',
    addTA: 'Add TA',
    taPermissions: 'TA Permissions',

    // Materials
    uploadMaterials: 'Upload Materials',
    courseMaterials: 'Course Materials',
    lectures: 'Lectures',
    notes: 'Notes',
    resources: 'Resources',
    uploadFile: 'Upload File',
    dragAndDrop: 'Drag and Drop Files Here',
    supportedFormats: 'Supported formats: PDF, DOC, PPT, MP4, Images',
    fileUploaded: 'File uploaded successfully',

    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    submit: 'Submit',
    apply: 'Apply',
    reset: 'Reset',
    filter: 'Filter',
    sort: 'Sort',
    search: 'Search',
    noData: 'No data available',
    viewAll: 'View All',
    seeMore: 'See More',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    download: 'Download',
    upload: 'Upload',
    export: 'Export',
    import: 'Import',
    refresh: 'Refresh',
    date: 'Date',
    time: 'Time',
    actions: 'Actions',
    more: 'More',

    // ModernDashboard extras
    newBadge: '+2 New',
    highPriority: 'High Priority',
    total: 'Total',
    evyAiTeachingAssistant: 'Evy — AI Teaching Assistant',
    evyAssistantQuote:
      "Professor, I've drafted feedback for the Advanced Calculus submissions and flagged 3 students who might need a follow-up session.",
    reviewInsights: 'Review Insights',
    dismiss: 'Dismiss',
    coursePerformance: 'Course Performance',
    studentEngagement: 'Student Engagement',
    upcomingTeaching: 'Upcoming Teaching',
    noUpcomingClasses: 'No upcoming classes',
    quickActions: 'Quick Actions',
    materials: 'Materials',
    addTask: 'Add Task',
    helpDesk: 'Help Desk',
    noRecentActivity: 'No recent activity',

    // Labs
    labsManagement: 'Labs Management',
    labsDescription:
      'Create labs, manage submissions, track attendance, and use AI to assist lab evaluation.',
    createNewLab: 'Create New Lab',
    searchLabs: 'Search Labs...',
    viewSubmissions: 'View Submissions',
    editLab: 'Edit Lab',
    uploadInstructions: 'Upload Instructions',
    gradeLab: 'Grade Lab',
    aiAutoGrading: 'AI Auto-Grading',
    pending: 'Pending',
    labs: 'Labs',

    // Quizzes
    quizzesManagement: 'Quizzes Management',
    quizzesDescription:
      'Create quizzes, manage attempts, auto-generate questions, and review student performance.',
    createNewQuiz: 'Create New Quiz',
    searchQuizzes: 'Search Quizzes...',
    questions: 'Questions',
    attempted: 'Attempted',
    minDuration: 'Min Duration',
    viewAttempts: 'View Attempts',
    editQuiz: 'Edit Quiz',
    generateWithAI: 'Generate with AI',
    analyzeResults: 'Analyze Results',
    publish: 'Publish',
    scheduled: 'Scheduled',
    closed: 'Closed',

    // Schedule
    teachingSchedule: 'Teaching Schedule',
    scheduleDescription:
      'View lectures, labs, office hours, quizzes, and deadlines in one smart calendar.',
    month: 'Month',
    week: 'Week',
    day: 'Day',
    allEvents: 'All Events',
    eventTypeLabel: 'Event Type:',
    today: 'Today',
    upcomingTeachingEvents: 'Upcoming Teaching Events',
    evySchedulingAssistant: 'Evy - Smart Scheduling Assistant',
    scheduleAssistantDescription:
      'Automatically detect conflicts and suggest optimal teaching times.',
    detectConflicts: 'Detect Conflicts',
    optimizeSchedule: 'Optimize Schedule',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    totalHours: 'Total Hours:',
    conflicts: 'Conflicts:',
    loadingSchedule: 'Loading schedule...',
    scheduleLoadError: 'Could not load schedule data. Please try again.',
    noScheduleItems: 'No schedule items found for the selected period.',
    noEventsScheduled: 'No events scheduled',
    officeHoursNoEventsScheduled: 'No events scheduled',
    noUpcomingEvents: 'No upcoming events',
    classSessions: 'Class Sessions',
    exam: 'Exam',
    personalEvents: 'Personal Events',
    campusEvents: 'Campus Events',
    campusEventsSource: 'Campus Events:',
    allCampusEvents: 'All Campus Events',
    myCampusEvents: 'My Campus Events',
    locationTbd: 'Location TBD',
    unknownCourse: 'Unknown Course',
    dateLabel: 'Date:',
    timeLabel: 'Time:',
    locationLabel: 'Location:',
    typeLabel: 'Type:',
    mandatory: 'Mandatory',
    register: 'Register',
    unregister: 'Unregister',
    eventFull: 'Event Full',
    close: 'Close',
    campusEventRegisterSuccess: 'Registered successfully.',
    campusEventRegisterError: 'Registration failed.',
    campusEventUnregisterSuccess: 'Unregistered successfully.',
    campusEventUnregisterError: 'Unregister failed.',
    noSuggestionsFound: 'No suggestions found for this period.',
    suggestionsFound: 'Suggestions found',
    suggestionsLoadError: 'Could not load slot suggestions.',
    noBestSuggestion: 'No best slot available in this range.',
    bestSlot: 'Best slot',
    officeHoursModeLabel: 'Mode:',
    officeHoursAppointmentsLabel: 'Appointments:',
    officeHoursInPerson: 'In Person',
    officeHoursOnline: 'Online',
    officeHoursHybrid: 'Hybrid',

    // Analytics extras
    courseLabel: 'Course:',
    allMetrics: 'All Metrics',
    coursePerformanceOverview: 'Course Performance Overview',
    averageGradeLabel: 'Average Grade:',
    engagementAnalytics: 'Engagement Analytics',
    engagementRateLabel: 'Engagement Rate:',
    attendanceOverview: 'Attendance Overview',
    average: 'Average',
    lowPerformanceTopics: 'Low-Performance Topics',
    detected: 'Detected',
    flaggedStudents: 'Flagged Students',
    message: 'Message',
    courseComparison: 'Course Comparison',
    avgCompletionRateByCourse: 'Average Completion Rate by Course',
    aiInsightsPoweredByEvy: 'AI Insights — Powered by Evy',
    performanceImprovement: 'Performance Improvement',
    strugglingTopic: 'Struggling Topic',
    recommendation: 'Recommendation',
    generateTeachingPlan: 'Generate Teaching Plan',
    letAiCreatePlan: 'Let AI create a personalized plan.',
    sendFeedbackToStudents: 'Send Feedback to Students',

    // AI Tools extras
    aiTeachingToolbox: 'AI Teaching Toolbox',
    aiToolboxDescription:
      'Use AI to enhance teaching, grade automatically, generate quizzes, create materials, and detect student issues.',
    quizGenerator: 'Quiz Generator',
    quizGeneratorDescription: 'Generate MCQs, True/False, and short-answer questions.',
    difficultyLevel: 'Difficulty Level',
    fromLectureFile: 'From Lecture File',
    autoGradingEvy: 'Auto-Grading (Evy)',
    autoGradingDescription:
      'Automatically grade submissions, detect plagiarism, and create feedback.',
    autoGradeAll: 'Auto-Grade All',
    generateFeedback: 'Generate Feedback',
    analyzeSubmissions: 'Analyze Submissions',
    materialsGenerator: 'Materials Generator',
    materialsGeneratorDescription:
      'Upload a file or type a topic to generate slides, summaries, and explanations.',
    enterTopic: 'Enter Topic...',
    uploadMaterial: 'Upload Material',
    generateSlides: 'Generate Slides',
    generateSummary: 'Generate Summary',
    aiInsights: 'AI Insights',
    aiInsightsDescription: 'Identify struggling students, weak topics, and performance patterns.',
    viewDetails: 'View Details',
    sendTips: 'Send Tips',
    imageToTextOCR: 'Image to Text (OCR)',
    smartTeachingPlan: 'Smart Teaching Plan',
    smartTeachingPlanDescription:
      'Generate a personalized weekly teaching plan based on analytics.',
    generatePlan: 'Generate Plan',
    aiQuestionEditor: 'AI Question Editor',

    // Communication extras
    communicationDescription:
      'Manage announcements, interact with course chats, and message students easily.',
    searchAnnouncements: 'Search Announcements...',
    sendNotification: 'Send Notification',
    aiCommunicationAssistant: 'AI Communication Assistant — Powered by Evy',
    aiCommunicationDescription:
      'Let AI draft announcements, summarize long chats, and suggest responses to save you time.',
    generateAnnouncement: 'Generate Announcement',
    summarizeChat: 'Summarize Chat',
    suggestReply: 'Suggest Reply',

    // Settings
    profileSettings: 'Profile & Settings',
    profileSettingsDescription:
      'Manage your personal information, account preferences, teaching preferences, and security settings.',
    profileInformation: 'Profile Information',
    updateProfileDescription: 'Update your personal details and profile photo',
    changePhoto: 'Change Photo',
    fullName: 'Full Name',
    academicTitle: 'Academic Title',
    phoneNumber: 'Phone Number',
    department: 'Department',
    officeLocationLabel: 'Office Location',
    bioDescription: 'Bio / Short Description',
    bioPlaceholder:
      'Tell students about yourself, your research interests, and teaching philosophy...',
    saveChanges: 'Save Changes',
    accountSettings: 'Account Settings',
    accountSettingsDescription: 'Manage security, notifications, and preferences',
    passwordSecurity: 'Password & Security',
    changePassword: 'Change Password',
    twoFactorAuth: 'Two-Factor Authentication',
    twoFactorDescription: 'Add an extra layer of security',
    loginActivity: 'Login Activity',
    notificationPreferences: 'Notification Preferences',
    newAssignmentSubmissions: 'New Assignment Submissions',
    newMessages: 'New Messages',
    courseChatMentions: 'Course Chat Mentions',
    aiAssistantAlerts: 'AI Assistant Alerts',
    languagePreference: 'Language Preference',
    teachingPreferences: 'Teaching Preferences',
    teachingPreferencesDescription: 'Customize your teaching tools and AI settings',
    classroomPreferences: 'Classroom Preferences',
    showStudentAnalyticsLabel: 'Show Student Analytics on Course Page',
    enableAutoGradingLabel: 'Enable Auto-Grading Suggestions',
    enableSmartAttendanceLabel: 'Enable Smart Attendance Alerts',
    showStudentsAtRiskLabel: 'Show "Students at Risk" Panel',
    aiPreferences: 'AI Preferences',
    difficultyForQuizzes: 'Difficulty Level for Generated Quizzes',
    preferredExplanationStyle: 'Preferred Explanation Style',
    detailedWithExamples: 'Detailed with Examples',
    conciseAndDirect: 'Concise and Direct',
    stepByStep: 'Step-by-Step',
    defaultAiTone: 'Default AI Tone',
    professional: 'Professional',
    friendly: 'Friendly',
    formal: 'Formal',
    privacySharing: 'Privacy & Sharing',
    privacyDescription: 'Control who can access your information',
    allowTAsAccess: 'Allow TAs to access analytics',
    allowAutoAnnouncements: 'Allow auto-generated announcements',
    hideEmailFromStudents: 'Hide instructor email from students',
    dangerZone: 'Danger Zone',
    dangerZoneDescription: 'Irreversible actions — proceed with caution',
    deactivateAccount: 'Deactivate Account',
    deactivateDescription: 'Temporarily disable your account. You can reactivate it anytime.',
    deactivate: 'Deactivate',
    deleteAccount: 'Delete Account',
    deleteAccountDescription:
      'Permanently delete your account and all associated data. This cannot be undone.',

    // Discussion extras
    discussionForum: 'Discussion Forum',
    respondToQuestions: 'Respond to Questions',
    searchDiscussionsPlaceholder: 'Search Discussions...',
    replies: 'Replies',
    views: 'Views',
    ta: 'TA',
    instructorRole: 'Instructor',
    studentRole: 'Student',
    pin: 'Pin',
    unpin: 'Unpin',
    closeThread: 'Close Thread',
    answered: 'Answered',
    markAsAnswer: 'Mark as Answer',
    acceptedAnswer: 'Accepted Answer',
    writeReplyPlaceholder: 'Write a Reply...',
    reply: 'Reply',
    noDiscussionsFound: 'No discussions found.',

    // Assignments extras
    searchAssignments: 'Search Assignments...',
    allStatus: 'All Status',
    draft: 'Draft',
    open: 'Open',
    dueLabel: 'Due:',
    submissionsLabel: 'Submissions:',
    closeAction: 'Close',
    noAssignmentsMatch: 'No assignments match your search.',
    noAssignmentsForSection: 'No assignments for this section.',

    // Roster extras
    enrolledStudents: 'Enrolled Students',
    addStudent: 'Add Student',
    searchStudentsPlaceholder: 'Search by Name, Email, or Status...',
    toggleStatus: 'Toggle Status',
    noStudentsMatch: 'No students match your search.',
    noStudentsEnrolled: 'No students enrolled.',
    showingFirst100: 'Showing First 100 of',
    results: 'Results',

    // Waitlist extras
    waitingForEnrollment: 'Waiting for Enrollment',
    searchWaitlistPlaceholder: 'Search by Name, Email, or Date...',
    requestedDate: 'Requested Date',
    priority: 'Priority',
    approve: 'Approve',
    reject: 'Reject',
    noStudentsOnWaitlist: 'No students on waitlist.',

    // Grades extras
    grades: 'Grades',
    searchGradesPlaceholder: 'Search by Student, Assignment, or Email...',
    student: 'Student',
    assignment: 'Assignment',
    noGradesMatch: 'No grades match your search.',
    noGradesRecorded: 'No grades recorded.',

    // Attendance extras
    addRecord: 'Add Record',
    searchByDate: 'Search by Date...',
    attendancePercent: 'Attendance %',
    noAttendanceMatch: 'No attendance records match your search.',
    noAttendanceRecords: 'No attendance records.',

    // CoursesPage extras
    semesterLabel: 'Semester:',
    statusLabel: 'Status:',
    sortByLabel: 'Sort By:',
    searchCourses: 'Search Courses...',
    lectureAndLab: 'Lecture + Lab',
    nextLecture: 'Next Lecture',
    openCourse: 'Open Course',
    noCoursesFound: 'No courses found',
    tryAdjustingFilters: 'Try adjusting your filters',
    createFirstCourse: 'Get started by creating your first course',
    aiToolsForTeaching: 'AI Tools for Teaching',
    aiToolsDescription: 'Generate quizzes, summaries, and detect struggling students.',
    createQuiz: 'Create Quiz',
    analyzeCourse: 'Analyze Course',
    createNewCourse: 'Create New Course',
    all: 'All',

    // CourseDetail extras
    courseNotFound: 'Course not found',
    backToCourses: '← Back to Courses',
    overview: 'Overview',
    detailedGrades: 'Detailed Grades',
  },
  ar: {
    // Header
    search: 'بحث...',
    searchPlaceholder: 'البحث عن المقررات والطلاب والمواد...',
    notifications: 'الإشعارات',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    viewProfile: 'عرض الملف الشخصي',
    logout: 'تسجيل الخروج',

    // Sidebar
    dashboard: 'لوحة التحكم',
    courses: 'المقررات',
    students: 'الطلاب',
    attendance: 'الحضور',
    analytics: 'التحليلات',
    communication: 'التواصل',
    aiTools: 'أدوات الذكاء الاصطناعي',
    settings: 'الإعدادات',
    calendar: 'التقويم',
    grading: 'التصحيح',

    // Dashboard Overview
    welcomeBack: 'مرحباً بعودتك',
    instructorDashboard: 'لوحة تحكم المحاضر',
    overviewDescription:
      'إدارة مقرراتك، تتبع أداء الطلاب، والوصول إلى أدوات التدريس بالذكاء الاصطناعي.',
    todaySchedule: 'جدول اليوم',
    upcomingDeadlines: 'المواعيد النهائية القادمة',
    quickStats: 'إحصائيات سريعة',
    recentActivity: 'النشاط الأخير',

    // Stats
    totalStudents: 'إجمالي الطلاب',
    activeCourses: 'المقررات النشطة',
    avgAttendance: 'متوسط الحضور',
    pendingGrading: 'بانتظار التصحيح',
    assignmentsToGrade: 'واجبات للتصحيح',

    // Courses
    myCourses: 'مقرراتي',
    createCourse: 'إنشاء مقرر',
    courseManagement: 'إدارة المقررات',
    courseCode: 'رمز المقرر',
    courseName: 'اسم المقرر',
    semester: 'الفصل الدراسي',
    credits: 'الساعات المعتمدة',
    enrolled: 'المسجلين',
    capacity: 'السعة',
    schedule: 'الجدول',
    room: 'القاعة',
    status: 'الحالة',
    active: 'نشط',
    archived: 'مؤرشف',
    viewCourse: 'عرض المقرر',
    editCourse: 'تعديل المقرر',
    archiveCourse: 'أرشفة المقرر',
    courseDetails: 'تفاصيل المقرر',
    courseMaterials: 'مواد المقرر',
    courseSettings: 'إعدادات المقرر',

    // Students
    studentRoster: 'قائمة الطلاب',
    allStudents: 'جميع الطلاب',
    studentName: 'اسم الطالب',
    studentId: 'رقم الطالب',
    email: 'البريد الإلكتروني',
    grade: 'الدرجة',
    attendanceRate: 'نسبة الحضور',
    performance: 'الأداء',
    contactStudent: 'التواصل مع الطالب',
    atRisk: 'معرض للخطر',
    onTrack: 'على المسار',
    excellent: 'ممتاز',

    // Attendance
    attendanceManagement: 'إدارة الحضور',
    takeAttendance: 'تسجيل الحضور',
    attendanceHistory: 'سجل الحضور',
    present: 'حاضر',
    absent: 'غائب',
    late: 'متأخر',
    excused: 'معذور',
    markAttendance: 'تسجيل الحضور',
    aiAttendance: 'الحضور بالذكاء الاصطناعي',
    uploadPhoto: 'رفع صورة',
    detectStudents: 'اكتشاف الطلاب',
    confirmAttendance: 'تأكيد الحضور',
    attendanceRecords: 'سجلات الحضور',
    overallAttendance: 'الحضور الإجمالي',
    lowAttendanceWarning: 'تحذير انخفاض الحضور',

    // Analytics
    courseAnalytics: 'تحليلات المقرر',
    studentPerformance: 'أداء الطلاب',
    gradeDistribution: 'توزيع الدرجات',
    attendanceTrends: 'اتجاهات الحضور',
    topicsMastery: 'إتقان المواضيع',
    atRiskStudents: 'الطلاب المعرضون للخطر',
    performanceTrends: 'اتجاهات الأداء',
    exportReport: 'تصدير التقرير',
    generateReport: 'إنشاء تقرير',
    weeklyReport: 'تقرير أسبوعي',
    monthlyReport: 'تقرير شهري',
    semesterReport: 'تقرير الفصل',
    averageGrade: 'متوسط الدرجات',
    completionRate: 'نسبة الإنجاز',
    engagementScore: 'نقاط المشاركة',

    // Communication
    communicationCenter: 'مركز التواصل',
    announcements: 'الإعلانات',
    createAnnouncement: 'إنشاء إعلان',
    scheduleAnnouncement: 'جدولة إعلان',
    sendNow: 'إرسال الآن',
    scheduleFor: 'جدولة لـ',
    announcementTitle: 'العنوان',
    announcementContent: 'المحتوى',
    selectCourses: 'اختر المقررات',
    allCourses: 'جميع المقررات',
    directMessages: 'الرسائل المباشرة',
    courseChats: 'محادثات المقرر',
    sendMessage: 'إرسال رسالة',
    typeMessage: 'اكتب رسالة...',
    messageStudents: 'مراسلة الطلاب',
    messageTA: 'مراسلة المعيد',

    // AI Tools
    aiTeachingTools: 'أدوات التدريس بالذكاء الاصطناعي',
    aiPowered: 'مدعوم بالذكاء الاصطناعي',
    generateQuiz: 'إنشاء اختبار',
    generateQuestions: 'توليد الأسئلة',
    autoGrading: 'التصحيح التلقائي',
    contentSummarizer: 'ملخص المحتوى',
    lectureAssistant: 'مساعد المحاضرة',
    smartRecommendations: 'توصيات ذكية',
    voiceToText: 'تحويل الصوت إلى نص',
    imageToText: 'تحويل الصورة إلى نص',
    aiChatbot: 'روبوت المحادثة الذكي',
    difficulty: 'الصعوبة',
    easy: 'سهل',
    medium: 'متوسط',
    hard: 'صعب',
    numberOfQuestions: 'عدد الأسئلة',
    questionType: 'نوع السؤال',
    multipleChoice: 'اختيار من متعدد',
    trueFalse: 'صح/خطأ',
    shortAnswer: 'إجابة قصيرة',
    essay: 'مقالي',
    generateFromContent: 'توليد من المحتوى',
    uploadContent: 'رفع محتوى',
    pasteContent: 'لصق المحتوى',
    evyAssistant: 'مساعد إيفي الذكي',

    // Grading
    gradingCenter: 'مركز التصحيح',
    pendingSubmissions: 'التسليمات المعلقة',
    gradedSubmissions: 'التسليمات المصححة',
    autoGrade: 'تصحيح تلقائي',
    manualGrade: 'تصحيح يدوي',
    provideFeedback: 'تقديم ملاحظات',
    submitGrade: 'تسليم الدرجة',
    batchGrade: 'تصحيح جماعي',
    rubric: 'معيار التقييم',
    createRubric: 'إنشاء معيار',
    applyRubric: 'تطبيق المعيار',
    score: 'الدرجة',
    maxScore: 'الدرجة القصوى',
    feedback: 'الملاحظات',
    aiSuggestion: 'اقتراح الذكاء الاصطناعي',

    // Assignments
    assignments: 'الواجبات',
    createAssignment: 'إنشاء واجب',
    assignmentTitle: 'عنوان الواجب',
    description: 'الوصف',
    dueDate: 'تاريخ التسليم',
    points: 'النقاط',
    attachments: 'المرفقات',
    submissions: 'التسليمات',
    notSubmitted: 'لم يتم التسليم',
    submitted: 'تم التسليم',
    graded: 'تم التصحيح',
    lateSubmissions: 'التسليمات المتأخرة',
    allowLate: 'السماح بالتسليم المتأخر',
    latePenalty: 'خصم التأخير',

    // Calendar & Schedule
    academicCalendar: 'التقويم الأكاديمي',
    examSchedule: 'جدول الاختبارات',
    officeHours: 'ساعات المكتب',
    setOfficeHours: 'تحديد ساعات المكتب',
    classSchedule: 'جدول المحاضرات',
    addEvent: 'إضافة حدث',
    eventTitle: 'عنوان الحدث',
    eventDate: 'تاريخ الحدث',
    eventTime: 'وقت الحدث',
    eventLocation: 'الموقع',
    recurringEvent: 'حدث متكرر',

    // Registration & Settings
    registrationPeriod: 'فترة التسجيل',
    courseCapacity: 'سعة المقرر',
    waitlist: 'قائمة الانتظار',
    enableWaitlist: 'تفعيل قائمة الانتظار',
    waitlistCapacity: 'سعة قائمة الانتظار',
    prerequisites: 'المتطلبات السابقة',
    courseFeatures: 'ميزات المقرر',
    enableFeature: 'تفعيل',
    disableFeature: 'تعطيل',
    taCollaboration: 'التعاون مع المعيدين',
    addTA: 'إضافة معيد',
    taPermissions: 'صلاحيات المعيد',

    // Materials
    uploadMaterials: 'رفع المواد',
    lectures: 'المحاضرات',
    notes: 'الملاحظات',
    resources: 'الموارد',
    uploadFile: 'رفع ملف',
    dragAndDrop: 'اسحب وأفلت الملفات هنا',
    supportedFormats: 'الصيغ المدعومة: PDF, DOC, PPT, MP4, صور',
    fileUploaded: 'تم رفع الملف بنجاح',

    // Common
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجاح',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    close: 'إغلاق',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    submit: 'إرسال',
    apply: 'تطبيق',
    reset: 'إعادة تعيين',
    filter: 'تصفية',
    sort: 'ترتيب',
    noData: 'لا توجد بيانات',
    viewAll: 'عرض الكل',
    seeMore: 'المزيد',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    download: 'تنزيل',
    upload: 'رفع',
    export: 'تصدير',
    import: 'استيراد',
    refresh: 'تحديث',
    date: 'التاريخ',
    time: 'الوقت',
    actions: 'الإجراءات',
    more: 'المزيد',

    // ModernDashboard extras
    newBadge: '+2 جديد',
    highPriority: 'أولوية عالية',
    total: 'الإجمالي',
    evyAiTeachingAssistant: 'إيفي — مساعد التدريس الذكي',
    evyAssistantQuote:
      'أستاذ، لقد أعددت ملاحظات لتسليمات حساب التفاضل المتقدم وحددت 3 طلاب قد يحتاجون لجلسة متابعة.',
    reviewInsights: 'مراجعة التحليلات',
    dismiss: 'تجاهل',
    coursePerformance: 'أداء المقرر',
    studentEngagement: 'تفاعل الطلاب',
    upcomingTeaching: 'التدريس القادم',
    noUpcomingClasses: 'لا توجد محاضرات قادمة',
    quickActions: 'إجراءات سريعة',
    materials: 'المواد',
    addTask: 'إضافة مهمة',
    helpDesk: 'مكتب المساعدة',
    noRecentActivity: 'لا يوجد نشاط حديث',

    // Labs
    labsManagement: 'إدارة المعامل',
    labsDescription:
      'إنشاء المعامل، إدارة التسليمات، تتبع الحضور، واستخدام الذكاء الاصطناعي لتقييم المعامل.',
    createNewLab: 'إنشاء معمل جديد',
    searchLabs: 'البحث في المعامل...',
    viewSubmissions: 'عرض التسليمات',
    editLab: 'تعديل المعمل',
    uploadInstructions: 'رفع التعليمات',
    gradeLab: 'تصحيح المعمل',
    aiAutoGrading: 'التصحيح التلقائي بالذكاء الاصطناعي',
    pending: 'قيد الانتظار',
    labs: 'المعامل',

    // Quizzes
    quizzesManagement: 'إدارة الاختبارات',
    quizzesDescription:
      'إنشاء الاختبارات، إدارة المحاولات، توليد الأسئلة تلقائياً، ومراجعة أداء الطلاب.',
    createNewQuiz: 'إنشاء اختبار جديد',
    searchQuizzes: 'البحث في الاختبارات...',
    questions: 'الأسئلة',
    attempted: 'تمت المحاولة',
    minDuration: 'دقيقة المدة',
    viewAttempts: 'عرض المحاولات',
    editQuiz: 'تعديل الاختبار',
    generateWithAI: 'توليد بالذكاء الاصطناعي',
    analyzeResults: 'تحليل النتائج',
    publish: 'نشر',
    scheduled: 'مجدول',
    closed: 'مغلق',

    // Schedule
    teachingSchedule: 'جدول التدريس',
    scheduleDescription:
      'عرض المحاضرات والمعامل وساعات المكتب والاختبارات والمواعيد النهائية في تقويم ذكي واحد.',
    month: 'شهر',
    week: 'أسبوع',
    day: 'يوم',
    allEvents: 'جميع الأحداث',
    eventTypeLabel: 'نوع الحدث:',
    today: 'اليوم',
    upcomingTeachingEvents: 'أحداث التدريس القادمة',
    evySchedulingAssistant: 'إيفي - مساعد الجدولة الذكي',
    scheduleAssistantDescription: 'اكتشاف التعارضات تلقائياً واقتراح أفضل أوقات التدريس.',
    detectConflicts: 'اكتشاف التعارضات',
    optimizeSchedule: 'تحسين الجدول',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    totalHours: 'إجمالي الساعات:',
    conflicts: 'التعارضات:',
    loadingSchedule: 'جاري تحميل الجدول...',
    scheduleLoadError: 'تعذر تحميل بيانات الجدول. حاول مرة أخرى.',
    noScheduleItems: 'لا توجد عناصر جدول في الفترة المحددة.',
    noEventsScheduled: 'لا توجد أحداث مجدولة',
    officeHoursNoEventsScheduled: 'لا توجد أحداث مجدولة',
    noUpcomingEvents: 'لا توجد أحداث قادمة',
    classSessions: 'جلسات المحاضرات',
    exam: 'اختبار',
    personalEvents: 'الأحداث الشخصية',
    campusEvents: 'أحداث الحرم',
    campusEventsSource: 'مصدر أحداث الحرم:',
    allCampusEvents: 'كل أحداث الحرم',
    myCampusEvents: 'أحداثي في الحرم',
    locationTbd: 'الموقع غير محدد',
    unknownCourse: 'مقرر غير معروف',
    dateLabel: 'التاريخ:',
    timeLabel: 'الوقت:',
    locationLabel: 'الموقع:',
    typeLabel: 'النوع:',
    mandatory: 'إلزامي',
    register: 'تسجيل',
    unregister: 'إلغاء التسجيل',
    eventFull: 'الحدث مكتمل',
    close: 'إغلاق',
    campusEventRegisterSuccess: 'تم التسجيل بنجاح.',
    campusEventRegisterError: 'فشل التسجيل.',
    campusEventUnregisterSuccess: 'تم إلغاء التسجيل بنجاح.',
    campusEventUnregisterError: 'فشل إلغاء التسجيل.',
    noSuggestionsFound: 'لم يتم العثور على اقتراحات في هذه الفترة.',
    suggestionsFound: 'تم العثور على اقتراحات',
    suggestionsLoadError: 'تعذر تحميل اقتراحات المواعيد.',
    noBestSuggestion: 'لا يوجد موعد أفضل في هذه الفترة.',
    bestSlot: 'أفضل موعد',
    officeHoursModeLabel: 'الوضع:',
    officeHoursAppointmentsLabel: 'الحجوزات:',
    officeHoursInPerson: 'حضوري',
    officeHoursOnline: 'عن بُعد',
    officeHoursHybrid: 'هجين',

    // Analytics extras
    courseLabel: 'المقرر:',
    allMetrics: 'جميع المقاييس',
    coursePerformanceOverview: 'نظرة عامة على أداء المقرر',
    averageGradeLabel: 'متوسط الدرجات:',
    engagementAnalytics: 'تحليلات التفاعل',
    engagementRateLabel: 'نسبة التفاعل:',
    attendanceOverview: 'نظرة عامة على الحضور',
    average: 'المتوسط',
    lowPerformanceTopics: 'المواضيع ضعيفة الأداء',
    detected: 'تم الاكتشاف',
    flaggedStudents: 'طلاب تم تحديدهم',
    message: 'رسالة',
    courseComparison: 'مقارنة المقررات',
    avgCompletionRateByCourse: 'متوسط نسبة الإنجاز حسب المقرر',
    aiInsightsPoweredByEvy: 'تحليلات الذكاء الاصطناعي — مدعوم من إيفي',
    performanceImprovement: 'تحسن الأداء',
    strugglingTopic: 'موضوع صعب',
    recommendation: 'توصية',
    generateTeachingPlan: 'إنشاء خطة تدريس',
    letAiCreatePlan: 'دع الذكاء الاصطناعي ينشئ خطة مخصصة.',
    sendFeedbackToStudents: 'إرسال ملاحظات للطلاب',

    // AI Tools extras
    aiTeachingToolbox: 'صندوق أدوات التدريس الذكي',
    aiToolboxDescription:
      'استخدم الذكاء الاصطناعي لتعزيز التدريس والتصحيح التلقائي وتوليد الاختبارات وإنشاء المواد واكتشاف مشاكل الطلاب.',
    quizGenerator: 'مولد الاختبارات',
    quizGeneratorDescription: 'توليد أسئلة اختيار من متعدد وصح/خطأ وإجابة قصيرة.',
    difficultyLevel: 'مستوى الصعوبة',
    fromLectureFile: 'من ملف المحاضرة',
    autoGradingEvy: 'التصحيح التلقائي (إيفي)',
    autoGradingDescription: 'تصحيح التسليمات تلقائياً واكتشاف الانتحال وإنشاء الملاحظات.',
    autoGradeAll: 'تصحيح الكل تلقائياً',
    generateFeedback: 'إنشاء ملاحظات',
    analyzeSubmissions: 'تحليل التسليمات',
    materialsGenerator: 'مولد المواد',
    materialsGeneratorDescription: 'ارفع ملفاً أو اكتب موضوعاً لتوليد شرائح وملخصات وشروحات.',
    enterTopic: 'أدخل الموضوع...',
    uploadMaterial: 'رفع مادة',
    generateSlides: 'توليد شرائح',
    generateSummary: 'توليد ملخص',
    aiInsights: 'تحليلات ذكية',
    aiInsightsDescription: 'تحديد الطلاب المتعثرين والمواضيع الضعيفة وأنماط الأداء.',
    viewDetails: 'عرض التفاصيل',
    sendTips: 'إرسال نصائح',
    imageToTextOCR: 'تحويل الصورة إلى نص (OCR)',
    smartTeachingPlan: 'خطة التدريس الذكية',
    smartTeachingPlanDescription: 'إنشاء خطة تدريس أسبوعية مخصصة بناءً على التحليلات.',
    generatePlan: 'إنشاء خطة',
    aiQuestionEditor: 'محرر الأسئلة الذكي',

    // Communication extras
    communicationDescription: 'إدارة الإعلانات والتفاعل مع محادثات المقرر ومراسلة الطلاب بسهولة.',
    searchAnnouncements: 'البحث في الإعلانات...',
    sendNotification: 'إرسال إشعار',
    aiCommunicationAssistant: 'مساعد التواصل الذكي — مدعوم من إيفي',
    aiCommunicationDescription:
      'دع الذكاء الاصطناعي يصوغ الإعلانات ويلخص المحادثات الطويلة ويقترح الردود لتوفير وقتك.',
    generateAnnouncement: 'إنشاء إعلان',
    summarizeChat: 'تلخيص المحادثة',
    suggestReply: 'اقتراح رد',

    // Settings
    profileSettings: 'الملف الشخصي والإعدادات',
    profileSettingsDescription:
      'إدارة معلوماتك الشخصية وتفضيلات الحساب وتفضيلات التدريس وإعدادات الأمان.',
    profileInformation: 'المعلومات الشخصية',
    updateProfileDescription: 'تحديث بياناتك الشخصية وصورة الملف الشخصي',
    changePhoto: 'تغيير الصورة',
    fullName: 'الاسم الكامل',
    academicTitle: 'اللقب الأكاديمي',
    phoneNumber: 'رقم الهاتف',
    department: 'القسم',
    officeLocationLabel: 'موقع المكتب',
    bioDescription: 'النبذة / الوصف المختصر',
    bioPlaceholder: 'أخبر الطلاب عن نفسك واهتماماتك البحثية وفلسفتك في التدريس...',
    saveChanges: 'حفظ التغييرات',
    accountSettings: 'إعدادات الحساب',
    accountSettingsDescription: 'إدارة الأمان والإشعارات والتفضيلات',
    passwordSecurity: 'كلمة المرور والأمان',
    changePassword: 'تغيير كلمة المرور',
    twoFactorAuth: 'المصادقة الثنائية',
    twoFactorDescription: 'إضافة طبقة أمان إضافية',
    loginActivity: 'نشاط تسجيل الدخول',
    notificationPreferences: 'تفضيلات الإشعارات',
    newAssignmentSubmissions: 'تسليمات الواجبات الجديدة',
    newMessages: 'رسائل جديدة',
    courseChatMentions: 'الإشارات في محادثات المقرر',
    aiAssistantAlerts: 'تنبيهات مساعد الذكاء الاصطناعي',
    languagePreference: 'تفضيل اللغة',
    teachingPreferences: 'تفضيلات التدريس',
    teachingPreferencesDescription: 'تخصيص أدوات التدريس وإعدادات الذكاء الاصطناعي',
    classroomPreferences: 'تفضيلات الفصل الدراسي',
    showStudentAnalyticsLabel: 'عرض تحليلات الطلاب في صفحة المقرر',
    enableAutoGradingLabel: 'تفعيل اقتراحات التصحيح التلقائي',
    enableSmartAttendanceLabel: 'تفعيل تنبيهات الحضور الذكية',
    showStudentsAtRiskLabel: 'عرض لوحة "الطلاب المعرضون للخطر"',
    aiPreferences: 'تفضيلات الذكاء الاصطناعي',
    difficultyForQuizzes: 'مستوى الصعوبة للاختبارات المولدة',
    preferredExplanationStyle: 'أسلوب الشرح المفضل',
    detailedWithExamples: 'مفصل مع أمثلة',
    conciseAndDirect: 'موجز ومباشر',
    stepByStep: 'خطوة بخطوة',
    defaultAiTone: 'نبرة الذكاء الاصطناعي الافتراضية',
    professional: 'مهني',
    friendly: 'ودي',
    formal: 'رسمي',
    privacySharing: 'الخصوصية والمشاركة',
    privacyDescription: 'التحكم في من يمكنه الوصول إلى معلوماتك',
    allowTAsAccess: 'السماح للمعيدين بالوصول إلى التحليلات',
    allowAutoAnnouncements: 'السماح بالإعلانات المولدة تلقائياً',
    hideEmailFromStudents: 'إخفاء البريد الإلكتروني عن الطلاب',
    dangerZone: 'منطقة الخطر',
    dangerZoneDescription: 'إجراءات لا رجعة فيها — تابع بحذر',
    deactivateAccount: 'تعطيل الحساب',
    deactivateDescription: 'تعطيل حسابك مؤقتاً. يمكنك إعادة تفعيله في أي وقت.',
    deactivate: 'تعطيل',
    deleteAccount: 'حذف الحساب',
    deleteAccountDescription: 'حذف حسابك نهائياً وجميع البيانات المرتبطة. لا يمكن التراجع عن هذا.',

    // Assignments extras
    searchAssignments: 'البحث في الواجبات...',
    allStatus: 'جميع الحالات',
    draft: 'مسودة',
    open: 'مفتوح',
    dueLabel: 'الموعد:',
    submissionsLabel: 'التسليمات:',
    closeAction: 'إغلاق',
    noAssignmentsMatch: 'لا توجد واجبات مطابقة للبحث.',
    noAssignmentsForSection: 'لا توجد واجبات لهذا القسم.',

    // Roster extras
    enrolledStudents: 'الطلاب المسجلين',
    addStudent: 'إضافة طالب',
    searchStudentsPlaceholder: 'البحث بالاسم أو البريد أو الحالة...',
    toggleStatus: 'تبديل الحالة',
    noStudentsMatch: 'لا يوجد طلاب مطابقين للبحث.',
    noStudentsEnrolled: 'لا يوجد طلاب مسجلين.',
    showingFirst100: 'عرض أول 100 من',
    results: 'نتيجة',

    // Waitlist extras
    waitingForEnrollment: 'في انتظار التسجيل',
    searchWaitlistPlaceholder: 'البحث بالاسم أو البريد أو التاريخ...',
    requestedDate: 'تاريخ الطلب',
    priority: 'الأولوية',
    approve: 'قبول',
    reject: 'رفض',
    noStudentsOnWaitlist: 'لا يوجد طلاب في قائمة الانتظار.',

    // Grades extras
    grades: 'الدرجات',
    searchGradesPlaceholder: 'البحث بالطالب أو الواجب أو البريد...',
    student: 'الطالب',
    assignment: 'الواجب',
    noGradesMatch: 'لا توجد درجات مطابقة للبحث.',
    noGradesRecorded: 'لا توجد درجات مسجلة.',

    // Attendance extras
    addRecord: 'إضافة سجل',
    searchByDate: 'البحث بالتاريخ...',
    attendancePercent: 'نسبة الحضور',
    noAttendanceMatch: 'لا توجد سجلات حضور مطابقة للبحث.',
    noAttendanceRecords: 'لا توجد سجلات حضور.',

    // Discussion extras
    discussionForum: 'منتدى المناقشة',
    respondToQuestions: 'الرد على الأسئلة',
    searchDiscussionsPlaceholder: 'بحث في المناقشات...',
    replies: 'ردود',
    views: 'مشاهدات',
    ta: 'معيد',
    instructorRole: 'محاضر',
    studentRole: 'طالب',
    pin: 'تثبيت',
    unpin: 'إلغاء التثبيت',
    closeThread: 'إغلاق المحادثة',
    answered: 'تمت الإجابة',
    markAsAnswer: 'تحديد كإجابة',
    acceptedAnswer: 'إجابة معتمدة',
    writeReplyPlaceholder: 'اكتب رداً...',
    reply: 'رد',
    noDiscussionsFound: 'لا توجد مناقشات.',

    // CoursesPage extras
    semesterLabel: 'الفصل:',
    statusLabel: 'الحالة:',
    sortByLabel: 'ترتيب حسب:',
    searchCourses: 'البحث في المقررات...',
    lectureAndLab: 'محاضرة + معمل',
    nextLecture: 'المحاضرة القادمة',
    openCourse: 'فتح المقرر',
    noCoursesFound: 'لم يتم العثور على مقررات',
    tryAdjustingFilters: 'حاول تعديل عوامل التصفية',
    createFirstCourse: 'ابدأ بإنشاء مقررك الأول',
    aiToolsForTeaching: 'أدوات الذكاء الاصطناعي للتدريس',
    aiToolsDescription: 'توليد الاختبارات والملخصات واكتشاف الطلاب المتعثرين.',
    createQuiz: 'إنشاء اختبار',
    analyzeCourse: 'تحليل المقرر',
    createNewCourse: 'إنشاء مقرر جديد',
    all: 'الكل',

    // CourseDetail extras
    courseNotFound: 'المقرر غير موجود',
    backToCourses: '→ العودة إلى المقررات',
    overview: 'نظرة عامة',
    detailedGrades: 'الدرجات التفصيلية',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('eduverse-language');
      return (saved as Language) || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('eduverse-language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
