export { default as Sidebar } from './Sidebar';
export { default as Header } from './Header';
export { default as StatsCard } from './StatsCard';
export { default as GpaChart } from './GpaChart';
export { default as DailySchedule } from './DailySchedule';
export { default as TodayClassesWidget } from './TodayClassesWidget';
export { default as PaymentHistory } from './PaymentHistory';
export { default as ClassTab } from './ClassTab';
export { default as WeeklySchedule } from './WeeklySchedule';
export { default as GradesTranscript } from './GradesTranscript';
// New modular assignments implementation
export { AssignmentsPage as Assignments } from './assignments';
// Legacy exports removed - AssignmentDetails integrated into AssignmentsPage
export { default as AcademicCalendar } from './AcademicCalendar';
export { default as ClassSchedule } from './ClassSchedule';
export { AIFeatures } from './AIFeatures';
export { AttendanceOverview } from './AttendanceOverview';
export { SmartTodoReminder } from './SmartTodoReminder';
export { CourseRegistration } from './CourseRegistration';
export { Gamification } from './Gamification';
export { NotificationCenter } from './NotificationCenter';
export { CourseCommunity } from './CourseCommunity';
export { LabInstructions } from './LabInstructions';
export { GlobalSearch } from './GlobalSearch';
export { SettingsPreferences } from './SettingsPreferences';
export { AINotes } from './AINotes';
export { QuizTaking } from './QuizTaking';
export { QuizzesTab } from './quizzes';
export { GradeAnalysis } from './GradeAnalysis';
export { Announcements } from './Announcements';
