import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

// Comprehensive translations for the student dashboard
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    search: 'Search...',
    searchPlaceholder: 'Search courses, assignments, materials...',
    notifications: 'Notifications',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    viewProfile: 'View Profile',

    // Sidebar
    dashboard: 'Dashboard',
    myClass: 'My Class',
    registration: 'Registration',
    community: 'Community',
    schedule: 'Schedule',
    assignments: 'Assignments',
    labSessions: 'Lab Sessions',
    grades: 'Grades',
    attendance: 'Attendance',
    analytics: 'Analytics',
    todoList: 'Todo List',
    aiFeatures: 'AI Features',
    achievements: 'Achievements',
    payments: 'Payments',
    chat: 'Chat',
    settings: 'Settings',

    // Dashboard
    welcomeBack: 'Welcome back',
    semesterSummary: 'Semester Summary',
    currentGPA: 'Current GPA',
    completedCredits: 'Completed Credits',
    upcomingDeadlines: 'Upcoming Deadlines',
    todaySchedule: "Today's Schedule",
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',

    // StatsCard
    outOf: 'out of',
    hours: 'hours',
    totalCredits: 'Total Credits',
    pendingTasks: 'Pending Tasks',
    tasks: 'tasks',

    // DailySchedule
    noClassesToday: 'No classes scheduled for today',
    room: 'Room',

    // ClassTab / My Courses
    myCourses: 'My Courses',
    enrolled: 'Enrolled',
    viewCourse: 'View Course',
    courseCode: 'Course Code',
    instructor: 'Instructor',
    credits: 'Credits',
    progress: 'Progress',
    viewAll: 'View All',
    courseMaterials: 'Course Materials',

    // Course Registration
    courseRegistration: 'Course Registration',
    availableCourses: 'Available Courses',
    registeredCourses: 'Registered Courses',
    register: 'Register',
    drop: 'Drop',
    prerequisites: 'Prerequisites',
    seats: 'Seats',
    seatsAvailable: 'seats available',
    full: 'Full',
    waitlist: 'Waitlist',
    registrationSuccess: 'Successfully registered',
    dropSuccess: 'Course dropped successfully',
    springTerm: 'Spring Term',
    fallTerm: 'Fall Term',
    summerTerm: 'Summer Term',

    // Assignments
    assignmentsDue: 'Assignments Due',
    submitted: 'Submitted',
    pending: 'Pending',
    overdue: 'Overdue',
    dueDate: 'Due Date',
    submit: 'Submit',
    viewDetails: 'View Details',
    allAssignments: 'All Assignments',
    uploadFile: 'Upload File',
      submitAssignment: 'Submit Assignment',
      submitYourWork: 'Submit Your Work',
      chooseHowToSubmit: 'Choose how you want to submit your work',
      submitYourType: 'Submit your {{type}} submission',
      backToAssignments: 'Back to Assignments',
      loadingAssignment: 'Loading assignment...',
      assignmentNotFound: 'Assignment not found',
      assignmentNotFoundDescription: "The assignment you're looking for doesn't exist or you don't have access to it.",
      writeYourResponse: 'Write your response here...',
      enterResponseToSubmit: 'Enter your response to submit',
      attachFileToSubmit: 'Attach a file to submit',
      enterValidUrlToSubmit: 'Enter a valid URL to submit',
      selectDriveFileToSubmit: 'Select a file from Google Drive',
      confirmSubmission: 'Confirm Submission',
      confirmSubmissionMessage: 'Are you sure you want to submit this assignment?',
      lateSubmissionMarked: 'This submission will be marked as late.',
      feedback: 'Feedback',
    deadline: 'Deadline',
    status: 'Status',
    graded: 'Graded',
    notSubmitted: 'Not Submitted',
    lateSubmission: 'Late Submission',
    daysLeft: 'days left',
    hoursLeft: 'hours left',

    // Grades & Transcript
    gradeHistory: 'Grade History',
    transcript: 'Transcript',
    gpaChart: 'GPA Chart',
    semester: 'Semester',
    grade: 'Grade',
    cumulativeGPA: 'Cumulative GPA',
    semesterGPA: 'Semester GPA',
    creditHours: 'Credit Hours',
    gradePoints: 'Grade Points',
    course: 'Course',
    letterGrade: 'Letter Grade',
    downloadTranscript: 'Download Transcript',
    officialTranscript: 'Official Transcript',
    gradesAndTranscript: 'Grades & Transcript',
    academicRecord: 'Academic Record',

    // Attendance
    attendanceOverview: 'Attendance Overview',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    excused: 'Excused',
    attendanceRate: 'Attendance Rate',
    totalClasses: 'Total Classes',
    attended: 'Attended',
    missed: 'Missed',
    attendanceHistory: 'Attendance History',
    lectureAttendance: 'Lecture Attendance',
    labAttendance: 'Lab Attendance',
    warning: 'Warning',
    attendanceWarning: 'Your attendance is below the required minimum',
    overallAttendance: 'Overall Attendance',

    // Schedule
    weeklySchedule: 'Weekly Schedule',
    classSchedule: 'Class Schedule',
    today: 'Today',
    tomorrow: 'Tomorrow',
    thisWeek: 'This Week',
    noClasses: 'No classes scheduled',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sun: 'Sun',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    lecture: 'Lecture',
    lab: 'Lab',
    tutorial: 'Tutorial',
    exam: 'Exam',
    allCourses: 'All Courses',
    allTypes: 'All Types',
    showWeekends: 'Show weekends',
    exportICal: 'Export iCal',
    scheduleConflictsDetected: 'Schedule conflicts detected',
    overlappingSlotsFound: 'overlapping slot(s) were found',
    allScheduleTypes: 'All schedule types',
    viewAll: 'View all',
    nowLabel: 'Now',
    nextUp: 'Next up',

    // AI Features
    aiAssistant: 'AI Assistant',
    aiPoweredTools: 'AI-Powered Learning Tools',
    summarizeNotes: 'Summarize Notes',
    generateQuiz: 'Generate Quiz',
    createFlashcards: 'Create Flashcards',
    studyRecommendations: 'Study Recommendations',
    voiceToText: 'Voice to Text',
    imageToText: 'Image to Text',
    aiChatbot: 'AI Chatbot',
    askQuestion: 'Ask a question...',
    generateSummary: 'Generate Summary',
    startQuiz: 'Start Quiz',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    numberOfQuestions: 'Number of Questions',
    flashcardDeck: 'Flashcard Deck',
    flip: 'Flip',
    correct: 'Correct',
    incorrect: 'Incorrect',
    noteSummarizer: 'Note Summarizer',
    quizGenerator: 'Quiz Generator',
    personalizedRecommendations: 'Personalized Recommendations',

    // Gamification
    points: 'Points',
    badges: 'Badges',
    leaderboard: 'Leaderboard',
    rank: 'Rank',
    earnedBadges: 'Earned Badges',
    totalPoints: 'Total Points',
    level: 'Level',
    xpToNextLevel: 'XP to Next Level',
    unlocked: 'Unlocked',
    locked: 'Locked',
    streak: 'Streak',
    daysStreak: 'Day Streak',
    weeklyGoal: 'Weekly Goal',
    challengeFriend: 'Challenge a Friend',
    yourRank: 'Your Rank',
    topStudents: 'Top Students',
    gamificationAchievements: 'Achievements & Rewards',

    // Community
    discussions: 'Discussions',
    announcements: 'Announcements',
    studyGroups: 'Study Groups',
    joinDiscussion: 'Join Discussion',
    postQuestion: 'Post a Question',
    newPost: 'New Post',
    reply: 'Reply',
    replies: 'Replies',
    like: 'Like',
    likes: 'Likes',
    share: 'Share',
    members: 'Members',
    joinGroup: 'Join Group',
    leaveGroup: 'Leave Group',
    createGroup: 'Create Group',
    groupName: 'Group Name',
    groupDescription: 'Group Description',
    courseCommunity: 'Course Community',

    // Labs
    labInstructions: 'Lab Instructions',
    labObjectives: 'Lab Objectives',
    resources: 'Resources',
    deliverables: 'Deliverables',
    submitDeliverable: 'Submit Deliverable',
    labReport: 'Lab Report',
    dueIn: 'Due in',
    labMaterials: 'Lab Materials',
    safetyGuidelines: 'Safety Guidelines',
    equipmentNeeded: 'Equipment Needed',
    procedure: 'Procedure',
    step: 'Step',
    labSession: 'Lab Session',

    // Analytics
    progressAnalytics: 'Progress & Analytics',
    studyHours: 'Study Hours',
    tasksCompleted: 'Tasks Completed',
    weakTopics: 'Topics to Review',
    strongTopics: 'Strong Topics',
    weeklyProgress: 'Weekly Progress',
    monthlyProgress: 'Monthly Progress',
    performanceTrend: 'Performance Trend',
    averageScore: 'Average Score',
    timeSpent: 'Time Spent',
    completionRate: 'Completion Rate',
    improvementAreas: 'Areas for Improvement',
    yourProgress: 'Your Progress',

    // Todo
    todoReminder: 'Todo & Reminders',
    addTask: 'Add Task',
    completed: 'Completed',
    inProgress: 'In Progress',
    priority: 'Priority',
    high: 'High',
    low: 'Low',
    taskTitle: 'Task Title',
    taskDescription: 'Task Description',
    setReminder: 'Set Reminder',
    reminderSet: 'Reminder Set',
    markComplete: 'Mark Complete',
    deleteTask: 'Delete Task',
    allTasks: 'All Tasks',
    todayTasks: "Today's Tasks",
    upcomingTasks: 'Upcoming Tasks',
    smartTodo: 'Smart Todo List',

    // Notifications
    allNotifications: 'All Notifications',
    unread: 'Unread',
    markAllRead: 'Mark All as Read',
    markAsRead: 'Mark as Read',
    notificationSettings: 'Notification Settings',
    noNotifications: 'No notifications',
    newNotification: 'New Notification',
    notificationCenter: 'Notification Center',

    // Chat / Messaging
    messages: 'Messages',
    sendMessage: 'Send Message',
    typeMessage: 'Type a message...',
    online: 'Online',
    offline: 'Offline',
    lastSeen: 'Last seen',
    newConversation: 'New Conversation',
    searchContacts: 'Search contacts...',
    noMessages: 'No messages yet',
    instructors: 'Instructors',
    classmates: 'Classmates',
    teachingAssistants: 'Teaching Assistants',
    messagingChat: 'Messaging',

    // Payments
    paymentHistory: 'Payment History',
    tuitionFees: 'Tuition & Fees',
    totalDue: 'Total Due',
    paid: 'Paid',
    unpaid: 'Unpaid',
    paymentDate: 'Payment Date',
    amount: 'Amount',
    paymentMethod: 'Payment Method',
    invoice: 'Invoice',
    downloadInvoice: 'Download Invoice',
    makePayment: 'Make Payment',
    paymentPlan: 'Payment Plan',
    financialAid: 'Financial Aid',
    scholarships: 'Scholarships',

    // Settings
    settingsPreferences: 'Settings & Preferences',
    customizeExperience: 'Customize your learning experience',
    appearance: 'Appearance',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    security: 'Security',
    twoFactorAuth: 'Two-Factor Authentication',
    twoFactorDesc: 'Add an extra layer of security to your account',
    enable2FA: 'Enable 2FA',
    disable2FA: 'Disable 2FA',
    privacy: 'Privacy',
    showOnlineStatus: 'Show Online Status',
    showActivityStatus: 'Show Activity Status',
    shareProgress: 'Share Progress with Classmates',
    accessibility: 'Accessibility',
    fontSize: 'Font Size',
    small: 'Small',
    large: 'Large',
    highContrast: 'High Contrast Mode',
    reduceMotion: 'Reduce Motion',
    offlineAccess: 'Offline Access',
    downloadMaterials: 'Download Materials',
    autoDownload: 'Auto-download Course Materials',
    wifiOnly: 'Download on Wi-Fi Only',
    storage: 'Storage',
    storageUsed: 'Used',
    clearCache: 'Clear Cache',
    downloadedItems: 'Downloaded Items',
    download: 'Download',
    remove: 'Remove',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    emailNotifications: 'Email Notifications',
    pushNotifications: 'Push Notifications',
    soundAlerts: 'Sound Alerts',
    deadlineReminders: 'Deadline Reminders',
    gradeUpdates: 'Grade Updates',

    // Global Search
    globalSearch: 'Global Search',
    searchResults: 'Search Results',
    recentSearches: 'Recent Searches',
    noResults: 'No results found',
    courses: 'Courses',
    files: 'Files',
    people: 'People',

    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    submitting: 'Submitting...',
    seeAll: 'See All',
    noData: 'No data available',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    retry: 'Retry',
    refresh: 'Refresh',
    filter: 'Filter',
    sort: 'Sort',
    all: 'All',
    active: 'Active',
    inactive: 'Inactive',
    date: 'Date',
    time: 'Time',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    description: 'Description',
    details: 'Details',
    more: 'More',
    less: 'Less',
    showMore: 'Show More',
    showLess: 'Show Less',
    viewMore: 'View More',

    // Quiz flow
    skip: 'Skip',
    answered: 'Answered',
    skipped: 'Skipped',
    unanswered: 'Unanswered',
    current: 'Current',
    total: 'Total',
    legend: 'Legend',
    questionNavigator: 'Question Navigator',
    submitAnswers: 'Submit Answers',
    noQuestionsAvailable: 'No questions available',
    quizTimeExpired: 'Time is up. Submitting your quiz...',
    quizSubmittedSuccessfully: 'Quiz submitted successfully',
    quizSubmitFailed: 'Failed to submit quiz',
    exitConfirmTitle: 'Exit quiz?',
    exitConfirmMessage: 'Your progress is saved, but unanswered questions will remain unanswered.',
    submitConfirmTitle: 'Submit quiz?',
    submitConfirmMessage: 'Please review your answers before final submission.',
    unansweredWarning: 'You still have {{count}} unanswered question(s).',
    confirmSubmit: 'Confirm Submit',

    // StatsCard
    comparedToLastSemester: 'Compared To Last Semester',

    // DailySchedule
    dailyClassSchedule: 'Daily Class Schedule',
    scheduleForWeek: 'Schedule for your class in week',
    courseRoom: 'Course Room',
    courseCredits: 'Course Credits',

    // ClassTab
    totalCourses: 'Total Courses',
    enrolledCourses: 'Enrolled Courses',
    enrolledCoursesDesc: 'All courses you are currently enrolled in',
    materials: 'Materials',
    courseProgress: 'Course Progress',
    students: 'Students',

    // GpaChart
    gradePointAverage: 'Grade Point Average',
    gpaComparison: 'Comparison between your GPA and Average Student GPA',
    allSemesters: 'All Semesters',
    yourGPA: 'Your GPA',
    averageGPA: 'Average GPA',
    secondSemester2025: '2nd Semester 2025',

    // CourseRegistration
    springRegistration: 'Spring 2026 Registration',
    browseCourses: 'Browse and register for courses for the upcoming semester',
    creditsEnrolled: 'Credits Enrolled',
    coursesRegistered: 'Courses Registered',
    onWaitlist: 'On Waitlist',
    searchCoursePlaceholder: 'Search by course name, code, or instructor...',
    allDepartments: 'All Departments',
    computerScience: 'Computer Science',
    mathematics: 'Mathematics',
    physics: 'Physics',
    allLevels: 'All Levels',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    open: 'Open',
    closed: 'Closed',
    enrolled2: 'enrolled',
    registered: 'Registered',
    joinWaitlist: 'Join Waitlist',
    mySchedule: 'My Schedule',
    coursesCredits: 'courses',
    noCourses: 'No courses registered yet',
    browseToAdd: 'Browse the catalog to add courses',
    courseDetails: 'Course Details',
    capacity: 'Capacity',
    confirmRegistration: 'Confirm Registration',
    joinWaitlistQuestion: 'Join Waitlist?',
    registerConfirmText: 'You are about to register for',
    waitlistConfirmText: "This course is full. You'll be added to the waitlist for",
    creditLimitWarning: 'Credit Limit Warning',
    creditLimitText:
      'Adding this course will exceed your credit limit. You may need advisor approval.',

    // Assignments
    assignmentTracker: 'Assignment Tracker',
    stayOnTop: 'Stay on Top of Your Assignments',
    totalAssignments: 'Total Assignments',
    thisSemester: 'This semester',
    activeTasks: 'Active Tasks',
    needsAttention: 'Needs attention',
    activeAssignments: 'Active Assignments',
    trackManageWork: 'Track and manage your ongoing work',
    allCaughtUp: 'All Caught Up!',
    noPendingAssignments: 'You have no pending assignments at the moment',
    timeLeft: 'Time Left',
    worth: 'Worth',
    pts: 'pts',
    continueWork: 'Continue',
    dueToday: 'Due today',
    dueTomorrow: 'Due Tomorrow',
    days: 'days',
    completedAssignments: 'Completed Assignments',
    reviewSubmitted: 'Review your submitted and graded work',
    searchAssignments: 'Search assignments...',
    allStatus: 'All Status',
    assignment: 'Assignment',
    type: 'Type',
    score: 'Score',
    actions: 'Actions',
    needsWork: 'Needs Work',
    onTrack: 'On Track',
    excellent: 'Excellent',

    // WeeklySchedule
    upcomingClasses: 'Upcoming Classes',
    nextScheduledClasses: 'Your next scheduled classes',
    timeColumn: 'Time',

    // ProgressAnalytics
    analyticsDashboard: 'Analytics Dashboard',
    trackPerformance: 'Track your performance, identify weak areas, and optimize your study plan',
    tasksDone: 'Tasks Done',
    quizzes: 'Quizzes',
    thisWeekLabel: 'This week',
    thisWeek2: 'This week',
    thisMonth: 'This month',
    thisSemester2: 'This semester',
    weeklyStudyActivity: 'Weekly Study Activity',
    totalHours: 'Total Hours',
    quizzesTaken: 'Quizzes Taken',
    topicsToReview: 'Topics to Review',
    study: 'Study',
    noWeakTopics: 'No weak topics identified!',
    courseProgressOverview: 'Course Progress Overview',
    gpa: 'GPA',
    studied: 'studied',
    topicsNeedReview: 'topic(s) need review',
    needsImprovement: 'Needs Improvement',
    currentGrade: 'Current Grade',
    allOnTrack: 'All courses are on track!',
    excellentPerformance: 'Excellent Performance',
    keepWorking: 'Keep working to achieve excellence!',
    aiStudyRecommendations: 'AI-Powered Study Recommendations',
    optimalStudyTime: 'Optimal Study Time',
    optimalStudyDesc: "Based on your activity, you're most productive between",
    scheduleDifficult: 'Schedule difficult topics during this time',
    focusPriority: 'Focus Priority',
    prioritizeDesc: 'Prioritize',
    assignmentsDueWeak: 'assignments due + weak topics identified',
    keepItUp: 'Keep It Up!',
    streakDesc: "You're on a",
    dayStreak: 'day streak',
    meetingGoals: 'of meeting study goals',
    maintainConsistency: 'Maintain consistency for best results',
    currentGradeLabel: 'Current Grade',
    strongTopicsLabel: 'Strong Topics',

    // PaymentHistory
    paymentTuitionHistory: 'Payment & Tuition History',
    paymentHistoryDesc: 'Complete data about your payment and tuition history',
    viewAllPayment: 'View All Payment',
    paymentId: 'Payment ID',
    paymentCategory: 'Payment Category',
    paymentStatus: 'Payment Status',
    logout: 'Logout',
  },
  ar: {
    // Header
    search: 'بحث...',
    searchPlaceholder: 'البحث عن المقررات والواجبات والمواد...',
    notifications: 'الإشعارات',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    viewProfile: 'عرض الملف الشخصي',

    // Sidebar
    dashboard: 'لوحة التحكم',
    myClass: 'صفي',
    registration: 'التسجيل',
    community: 'المجتمع',
    schedule: 'الجدول',
    assignments: 'الواجبات',
    labSessions: 'جلسات المعمل',
    grades: 'الدرجات',
    attendance: 'الحضور',
    analytics: 'التحليلات',
    todoList: 'قائمة المهام',
    aiFeatures: 'ميزات الذكاء الاصطناعي',
    achievements: 'الإنجازات',
    payments: 'المدفوعات',
    chat: 'المحادثة',
    settings: 'الإعدادات',

    // Dashboard
    welcomeBack: 'مرحباً بعودتك',
    semesterSummary: 'ملخص الفصل الدراسي',
    currentGPA: 'المعدل التراكمي الحالي',
    completedCredits: 'الساعات المكتملة',
    upcomingDeadlines: 'المواعيد النهائية القادمة',
    todaySchedule: 'جدول اليوم',
    quickActions: 'إجراءات سريعة',
    recentActivity: 'النشاط الأخير',

    // StatsCard
    outOf: 'من',
    hours: 'ساعات',
    totalCredits: 'إجمالي الساعات',
    pendingTasks: 'المهام المعلقة',
    tasks: 'مهام',

    // DailySchedule
    noClassesToday: 'لا توجد محاضرات مجدولة لليوم',
    room: 'القاعة',

    // ClassTab / My Courses
    myCourses: 'مقرراتي',
    enrolled: 'مسجل',
    viewCourse: 'عرض المقرر',
    courseCode: 'رمز المقرر',
    instructor: 'المحاضر',
    credits: 'الساعات',
    progress: 'التقدم',
    viewAll: 'عرض الكل',
    courseMaterials: 'مواد المقرر',

    // Course Registration
    courseRegistration: 'تسجيل المقررات',
    availableCourses: 'المقررات المتاحة',
    registeredCourses: 'المقررات المسجلة',
    register: 'تسجيل',
    drop: 'حذف',
    prerequisites: 'المتطلبات السابقة',
    seats: 'المقاعد',
    seatsAvailable: 'مقاعد متاحة',
    full: 'مكتمل',
    waitlist: 'قائمة الانتظار',
    registrationSuccess: 'تم التسجيل بنجاح',
    dropSuccess: 'تم حذف المقرر بنجاح',
    springTerm: 'الفصل الربيعي',
    fallTerm: 'الفصل الخريفي',
    summerTerm: 'الفصل الصيفي',

    // Assignments
    assignmentsDue: 'الواجبات المستحقة',
    submitted: 'تم التسليم',
    pending: 'قيد الانتظار',
    overdue: 'متأخر',
    dueDate: 'تاريخ التسليم',
    submit: 'تسليم',
    viewDetails: 'عرض التفاصيل',
    allAssignments: 'جميع الواجبات',
    uploadFile: 'رفع ملف',
      submitAssignment: 'تسليم الواجب',
      submitYourWork: 'قدّم عملك',
      chooseHowToSubmit: 'اختر طريقة تسليم عملك',
      submitYourType: 'قدّم تسليم {{type}}',
      backToAssignments: 'العودة إلى الواجبات',
      loadingAssignment: 'جاري تحميل الواجب...',
      assignmentNotFound: 'لم يتم العثور على الواجب',
      assignmentNotFoundDescription: 'الواجب الذي تبحث عنه غير موجود أو لا تملك صلاحية الوصول إليه.',
      writeYourResponse: 'اكتب إجابتك هنا...',
      enterResponseToSubmit: 'أدخل إجابتك للتسليم',
      attachFileToSubmit: 'أرفق ملفاً للتسليم',
      enterValidUrlToSubmit: 'أدخل رابطاً صحيحاً للتسليم',
      selectDriveFileToSubmit: 'اختر ملفاً من Google Drive',
      confirmSubmission: 'تأكيد التسليم',
      confirmSubmissionMessage: 'هل أنت متأكد أنك تريد تسليم هذا الواجب؟',
      lateSubmissionMarked: 'سيتم اعتبار هذا التسليم متأخراً.',
      feedback: 'ملاحظات',
    deadline: 'الموعد النهائي',
    status: 'الحالة',
    graded: 'تم التصحيح',
    notSubmitted: 'لم يتم التسليم',
    lateSubmission: 'تسليم متأخر',
    daysLeft: 'أيام متبقية',
    hoursLeft: 'ساعات متبقية',

    // Grades & Transcript
    gradeHistory: 'سجل الدرجات',
    transcript: 'السجل الأكاديمي',
    gpaChart: 'رسم المعدل التراكمي',
    semester: 'الفصل الدراسي',
    grade: 'الدرجة',
    cumulativeGPA: 'المعدل التراكمي',
    semesterGPA: 'معدل الفصل',
    creditHours: 'الساعات المعتمدة',
    gradePoints: 'نقاط الدرجات',
    course: 'المقرر',
    letterGrade: 'التقدير',
    downloadTranscript: 'تحميل السجل الأكاديمي',
    officialTranscript: 'السجل الأكاديمي الرسمي',
    gradesAndTranscript: 'الدرجات والسجل الأكاديمي',
    academicRecord: 'السجل الأكاديمي',

    // Attendance
    attendanceOverview: 'نظرة عامة على الحضور',
    present: 'حاضر',
    absent: 'غائب',
    late: 'متأخر',
    excused: 'معذور',
    attendanceRate: 'نسبة الحضور',
    totalClasses: 'إجمالي المحاضرات',
    attended: 'حضر',
    missed: 'فائت',
    attendanceHistory: 'سجل الحضور',
    lectureAttendance: 'حضور المحاضرات',
    labAttendance: 'حضور المعامل',
    warning: 'تحذير',
    attendanceWarning: 'نسبة حضورك أقل من الحد الأدنى المطلوب',
    overallAttendance: 'الحضور الإجمالي',

    // Schedule
    weeklySchedule: 'الجدول الأسبوعي',
    classSchedule: 'جدول المحاضرات',
    today: 'اليوم',
    tomorrow: 'غداً',
    thisWeek: 'هذا الأسبوع',
    noClasses: 'لا توجد محاضرات مجدولة',
    sunday: 'الأحد',
    monday: 'الاثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    saturday: 'السبت',
    sun: 'أحد',
    mon: 'اثنين',
    tue: 'ثلاثاء',
    wed: 'أربعاء',
    thu: 'خميس',
    fri: 'جمعة',
    sat: 'سبت',
    lecture: 'محاضرة',
    lab: 'معمل',
    tutorial: 'تدريب',
    exam: 'اختبار',
    allCourses: 'كل المقررات',
    allTypes: 'كل الأنواع',
    showWeekends: 'إظهار نهاية الأسبوع',
    exportICal: 'تصدير iCal',
    scheduleConflictsDetected: 'تم اكتشاف تعارضات في الجدول',
    overlappingSlotsFound: 'تم العثور على تعارضات زمنية',
    allScheduleTypes: 'كل أنواع الجداول',
    viewAll: 'عرض الكل',
    nowLabel: 'الآن',
    nextUp: 'التالي',

    // AI Features
    aiAssistant: 'مساعد الذكاء الاصطناعي',
    aiPoweredTools: 'أدوات التعلم بالذكاء الاصطناعي',
    summarizeNotes: 'تلخيص الملاحظات',
    generateQuiz: 'إنشاء اختبار',
    createFlashcards: 'إنشاء بطاقات تعليمية',
    studyRecommendations: 'توصيات الدراسة',
    voiceToText: 'تحويل الصوت إلى نص',
    imageToText: 'تحويل الصورة إلى نص',
    aiChatbot: 'روبوت المحادثة الذكي',
    askQuestion: 'اطرح سؤالاً...',
    generateSummary: 'إنشاء ملخص',
    startQuiz: 'بدء الاختبار',
    difficulty: 'الصعوبة',
    easy: 'سهل',
    medium: 'متوسط',
    hard: 'صعب',
    numberOfQuestions: 'عدد الأسئلة',
    flashcardDeck: 'مجموعة البطاقات',
    flip: 'قلب',
    correct: 'صحيح',
    incorrect: 'خطأ',
    noteSummarizer: 'ملخص الملاحظات',
    quizGenerator: 'منشئ الاختبارات',
    personalizedRecommendations: 'توصيات مخصصة',

    // Gamification
    points: 'النقاط',
    badges: 'الشارات',
    leaderboard: 'لوحة المتصدرين',
    rank: 'الترتيب',
    earnedBadges: 'الشارات المكتسبة',
    totalPoints: 'إجمالي النقاط',
    level: 'المستوى',
    xpToNextLevel: 'XP للمستوى التالي',
    unlocked: 'مفتوح',
    locked: 'مقفل',
    streak: 'السلسلة',
    daysStreak: 'أيام متتالية',
    weeklyGoal: 'الهدف الأسبوعي',
    challengeFriend: 'تحدي صديق',
    yourRank: 'ترتيبك',
    topStudents: 'أفضل الطلاب',
    gamificationAchievements: 'الإنجازات والمكافآت',

    // Community
    discussions: 'المناقشات',
    announcements: 'الإعلانات',
    studyGroups: 'مجموعات الدراسة',
    joinDiscussion: 'انضم للمناقشة',
    postQuestion: 'اطرح سؤالاً',
    newPost: 'منشور جديد',
    reply: 'رد',
    replies: 'الردود',
    like: 'إعجاب',
    likes: 'الإعجابات',
    share: 'مشاركة',
    members: 'الأعضاء',
    joinGroup: 'انضم للمجموعة',
    leaveGroup: 'مغادرة المجموعة',
    createGroup: 'إنشاء مجموعة',
    groupName: 'اسم المجموعة',
    groupDescription: 'وصف المجموعة',
    courseCommunity: 'مجتمع المقرر',

    // Labs
    labInstructions: 'تعليمات المعمل',
    labObjectives: 'أهداف المعمل',
    resources: 'الموارد',
    deliverables: 'المخرجات',
    submitDeliverable: 'تسليم المخرج',
    labReport: 'تقرير المعمل',
    dueIn: 'يستحق في',
    labMaterials: 'مواد المعمل',
    safetyGuidelines: 'إرشادات السلامة',
    equipmentNeeded: 'المعدات المطلوبة',
    procedure: 'الإجراءات',
    step: 'خطوة',
    labSession: 'جلسة المعمل',

    // Analytics
    progressAnalytics: 'التقدم والتحليلات',
    studyHours: 'ساعات الدراسة',
    tasksCompleted: 'المهام المكتملة',
    weakTopics: 'مواضيع تحتاج مراجعة',
    strongTopics: 'المواضيع القوية',
    weeklyProgress: 'التقدم الأسبوعي',
    monthlyProgress: 'التقدم الشهري',
    performanceTrend: 'اتجاه الأداء',
    averageScore: 'متوسط الدرجات',
    timeSpent: 'الوقت المستغرق',
    completionRate: 'نسبة الإنجاز',
    improvementAreas: 'مجالات التحسين',
    yourProgress: 'تقدمك',

    // Todo
    todoReminder: 'المهام والتذكيرات',
    addTask: 'إضافة مهمة',
    completed: 'مكتمل',
    inProgress: 'قيد التنفيذ',
    priority: 'الأولوية',
    high: 'عالية',
    low: 'منخفضة',
    taskTitle: 'عنوان المهمة',
    taskDescription: 'وصف المهمة',
    setReminder: 'تعيين تذكير',
    reminderSet: 'تم تعيين التذكير',
    markComplete: 'تحديد كمكتمل',
    deleteTask: 'حذف المهمة',
    allTasks: 'جميع المهام',
    todayTasks: 'مهام اليوم',
    upcomingTasks: 'المهام القادمة',
    smartTodo: 'قائمة المهام الذكية',

    // Notifications
    allNotifications: 'جميع الإشعارات',
    unread: 'غير مقروء',
    markAllRead: 'تحديد الكل كمقروء',
    markAsRead: 'تحديد كمقروء',
    notificationSettings: 'إعدادات الإشعارات',
    noNotifications: 'لا توجد إشعارات',
    newNotification: 'إشعار جديد',
    notificationCenter: 'مركز الإشعارات',

    // Chat / Messaging
    messages: 'الرسائل',
    sendMessage: 'إرسال رسالة',
    typeMessage: 'اكتب رسالة...',
    online: 'متصل',
    offline: 'غير متصل',
    lastSeen: 'آخر ظهور',
    newConversation: 'محادثة جديدة',
    searchContacts: 'البحث في جهات الاتصال...',
    noMessages: 'لا توجد رسائل بعد',
    instructors: 'المحاضرون',
    classmates: 'زملاء الدراسة',
    teachingAssistants: 'المعيدون',
    messagingChat: 'المراسلة',

    // Payments
    paymentHistory: 'سجل المدفوعات',
    tuitionFees: 'الرسوم الدراسية',
    totalDue: 'إجمالي المستحق',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    paymentDate: 'تاريخ الدفع',
    amount: 'المبلغ',
    paymentMethod: 'طريقة الدفع',
    invoice: 'الفاتورة',
    downloadInvoice: 'تحميل الفاتورة',
    makePayment: 'إجراء دفعة',
    paymentPlan: 'خطة الدفع',
    financialAid: 'المساعدة المالية',
    scholarships: 'المنح الدراسية',

    // Settings
    settingsPreferences: 'الإعدادات والتفضيلات',
    customizeExperience: 'خصص تجربة التعلم الخاصة بك',
    appearance: 'المظهر',
    theme: 'السمة',
    light: 'فاتح',
    dark: 'داكن',
    system: 'النظام',
    security: 'الأمان',
    twoFactorAuth: 'المصادقة الثنائية',
    twoFactorDesc: 'أضف طبقة إضافية من الأمان لحسابك',
    enable2FA: 'تفعيل المصادقة الثنائية',
    disable2FA: 'إلغاء المصادقة الثنائية',
    privacy: 'الخصوصية',
    showOnlineStatus: 'إظهار حالة الاتصال',
    showActivityStatus: 'إظهار حالة النشاط',
    shareProgress: 'مشاركة التقدم مع زملاء الدراسة',
    accessibility: 'إمكانية الوصول',
    fontSize: 'حجم الخط',
    small: 'صغير',
    large: 'كبير',
    highContrast: 'وضع التباين العالي',
    reduceMotion: 'تقليل الحركة',
    offlineAccess: 'الوصول دون اتصال',
    downloadMaterials: 'تحميل المواد',
    autoDownload: 'تنزيل مواد الدورة تلقائياً',
    wifiOnly: 'التنزيل عبر Wi-Fi فقط',
    storage: 'التخزين',
    storageUsed: 'مستخدم',
    clearCache: 'مسح ذاكرة التخزين المؤقت',
    downloadedItems: 'العناصر المحملة',
    download: 'تنزيل',
    remove: 'إزالة',
    saveChanges: 'حفظ التغييرات',
    cancel: 'إلغاء',
    emailNotifications: 'إشعارات البريد الإلكتروني',
    pushNotifications: 'الإشعارات الفورية',
    soundAlerts: 'تنبيهات صوتية',
    deadlineReminders: 'تذكيرات المواعيد النهائية',
    gradeUpdates: 'تحديثات الدرجات',

    // Global Search
    globalSearch: 'البحث الشامل',
    searchResults: 'نتائج البحث',
    recentSearches: 'عمليات البحث الأخيرة',
    noResults: 'لا توجد نتائج',
    courses: 'المقررات',
    files: 'الملفات',
    people: 'الأشخاص',

    // Common
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجاح',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    close: 'إغلاق',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    submitting: 'جارٍ الإرسال...',
    seeAll: 'عرض الكل',
    noData: 'لا توجد بيانات',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    ok: 'موافق',
    retry: 'إعادة المحاولة',
    refresh: 'تحديث',
    filter: 'تصفية',
    sort: 'ترتيب',
    all: 'الكل',
    active: 'نشط',
    inactive: 'غير نشط',
    date: 'التاريخ',
    time: 'الوقت',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    description: 'الوصف',
    details: 'التفاصيل',
    more: 'المزيد',
    less: 'أقل',
    showMore: 'عرض المزيد',
    showLess: 'عرض أقل',
    viewMore: 'عرض المزيد',

    // Quiz flow
    skip: 'تخطي',
    answered: 'مجاب',
    skipped: 'متخطى',
    unanswered: 'غير مجاب',
    current: 'الحالي',
    total: 'الإجمالي',
    legend: 'الدليل',
    questionNavigator: 'متصفح الأسئلة',
    submitAnswers: 'إرسال الإجابات',
    noQuestionsAvailable: 'لا توجد أسئلة متاحة',
    quizTimeExpired: 'انتهى الوقت. جارٍ إرسال الاختبار...',
    quizSubmittedSuccessfully: 'تم إرسال الاختبار بنجاح',
    quizSubmitFailed: 'فشل إرسال الاختبار',
    exitConfirmTitle: 'الخروج من الاختبار؟',
    exitConfirmMessage: 'سيتم حفظ تقدمك، لكن الأسئلة غير المجابة ستبقى بدون إجابة.',
    submitConfirmTitle: 'إرسال الاختبار؟',
    submitConfirmMessage: 'يرجى مراجعة إجاباتك قبل الإرسال النهائي.',
    unansweredWarning: 'لا يزال لديك {{count}} سؤال/أسئلة غير مجابة.',
    confirmSubmit: 'تأكيد الإرسال',

    // StatsCard
    comparedToLastSemester: 'مقارنة بالفصل السابق',

    // DailySchedule
    dailyClassSchedule: 'الجدول اليومي للمحاضرات',
    scheduleForWeek: 'جدول محاضراتك هذا الأسبوع',
    courseRoom: 'قاعة المقرر',
    courseCredits: 'ساعات المقرر',

    // ClassTab
    totalCourses: 'إجمالي المقررات',
    enrolledCourses: 'المقررات المسجلة',
    enrolledCoursesDesc: 'جميع المقررات التي أنت مسجل فيها حالياً',
    materials: 'المواد',
    courseProgress: 'تقدم المقرر',
    students: 'طالب',

    // GpaChart
    gradePointAverage: 'المعدل التراكمي',
    gpaComparison: 'مقارنة بين معدلك التراكمي ومتوسط معدل الطلاب',
    allSemesters: 'جميع الفصول',
    yourGPA: 'معدلك التراكمي',
    averageGPA: 'المعدل العام',
    secondSemester2025: 'الفصل الثاني ٢٠٢٥',

    // CourseRegistration
    springRegistration: 'تسجيل فصل الربيع ٢٠٢٦',
    browseCourses: 'تصفح وسجل في المقررات للفصل الدراسي القادم',
    creditsEnrolled: 'الساعات المسجلة',
    coursesRegistered: 'المقررات المسجلة',
    onWaitlist: 'في قائمة الانتظار',
    searchCoursePlaceholder: 'ابحث باسم المقرر أو الرمز أو المحاضر...',
    allDepartments: 'جميع الأقسام',
    computerScience: 'علوم الحاسب',
    mathematics: 'الرياضيات',
    physics: 'الفيزياء',
    allLevels: 'جميع المستويات',
    beginner: 'مبتدئ',
    intermediate: 'متوسط',
    advanced: 'متقدم',
    open: 'مفتوح',
    closed: 'مغلق',
    enrolled2: 'مسجل',
    registered: 'مسجل',
    joinWaitlist: 'انضم لقائمة الانتظار',
    mySchedule: 'جدولي',
    coursesCredits: 'مقررات',
    noCourses: 'لا توجد مقررات مسجلة بعد',
    browseToAdd: 'تصفح الكتالوج لإضافة مقررات',
    courseDetails: 'تفاصيل المقرر',
    capacity: 'السعة',
    confirmRegistration: 'تأكيد التسجيل',
    joinWaitlistQuestion: 'الانضمام لقائمة الانتظار؟',
    registerConfirmText: 'أنت على وشك التسجيل في',
    waitlistConfirmText: 'هذا المقرر مكتمل. سيتم إضافتك لقائمة الانتظار لـ',
    creditLimitWarning: 'تحذير حد الساعات',
    creditLimitText:
      'إضافة هذا المقرر ستتجاوز الحد المسموح للساعات. قد تحتاج لموافقة المرشد الأكاديمي.',

    // Assignments
    assignmentTracker: 'متتبع الواجبات',
    stayOnTop: 'ابقَ على اطلاع بواجباتك',
    totalAssignments: 'إجمالي الواجبات',
    thisSemester: 'هذا الفصل',
    activeTasks: 'المهام النشطة',
    needsAttention: 'تحتاج انتباه',
    activeAssignments: 'الواجبات النشطة',
    trackManageWork: 'تتبع وإدارة أعمالك الجارية',
    allCaughtUp: 'لا توجد واجبات معلقة!',
    noPendingAssignments: 'ليس لديك واجبات معلقة في الوقت الحالي',
    timeLeft: 'الوقت المتبقي',
    worth: 'القيمة',
    pts: 'نقطة',
    continueWork: 'متابعة',
    dueToday: 'مستحق اليوم',
    dueTomorrow: 'مستحق غداً',
    days: 'أيام',
    completedAssignments: 'الواجبات المكتملة',
    reviewSubmitted: 'مراجعة الأعمال المسلمة والمصححة',
    searchAssignments: 'البحث في الواجبات...',
    allStatus: 'جميع الحالات',
    assignment: 'الواجب',
    type: 'النوع',
    score: 'الدرجة',
    actions: 'الإجراءات',
    needsWork: 'يحتاج تحسين',
    onTrack: 'على المسار',
    excellent: 'ممتاز',

    // WeeklySchedule
    upcomingClasses: 'المحاضرات القادمة',
    nextScheduledClasses: 'محاضراتك المجدولة القادمة',
    timeColumn: 'الوقت',

    // ProgressAnalytics
    analyticsDashboard: 'لوحة التحليلات',
    trackPerformance: 'تتبع أدائك، حدد نقاط الضعف، وحسّن خطة دراستك',
    tasksDone: 'المهام المنجزة',
    quizzes: 'الاختبارات',
    thisWeekLabel: 'هذا الأسبوع',
    thisWeek2: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    thisSemester2: 'هذا الفصل',
    weeklyStudyActivity: 'النشاط الدراسي الأسبوعي',
    totalHours: 'إجمالي الساعات',
    quizzesTaken: 'الاختبارات المأخوذة',
    topicsToReview: 'مواضيع تحتاج مراجعة',
    study: 'دراسة',
    noWeakTopics: 'لم يتم تحديد مواضيع ضعيفة!',
    courseProgressOverview: 'نظرة عامة على تقدم المقررات',
    gpa: 'المعدل',
    studied: 'تمت دراستها',
    topicsNeedReview: 'موضوع(ات) تحتاج مراجعة',
    needsImprovement: 'يحتاج تحسين',
    currentGrade: 'الدرجة الحالية',
    allOnTrack: 'جميع المقررات على المسار الصحيح!',
    excellentPerformance: 'أداء ممتاز',
    keepWorking: 'واصل العمل لتحقيق التميز!',
    aiStudyRecommendations: 'توصيات دراسية مدعومة بالذكاء الاصطناعي',
    optimalStudyTime: 'وقت الدراسة المثالي',
    optimalStudyDesc: 'بناءً على نشاطك، أنت أكثر إنتاجية بين',
    scheduleDifficult: 'جدول المواضيع الصعبة خلال هذا الوقت',
    focusPriority: 'أولوية التركيز',
    prioritizeDesc: 'أعطِ الأولوية لـ',
    assignmentsDueWeak: 'واجبات مستحقة + مواضيع ضعيفة محددة',
    keepItUp: 'استمر!',
    streakDesc: 'أنت في',
    dayStreak: 'يوم متتالي',
    meetingGoals: 'من تحقيق أهداف الدراسة',
    maintainConsistency: 'حافظ على الاستمرارية لأفضل النتائج',
    currentGradeLabel: 'الدرجة الحالية',
    strongTopicsLabel: 'المواضيع القوية',

    // PaymentHistory
    paymentTuitionHistory: 'سجل المدفوعات والرسوم الدراسية',
    paymentHistoryDesc: 'بيانات كاملة عن سجل المدفوعات والرسوم الدراسية',
    viewAllPayment: 'عرض جميع المدفوعات',
    paymentId: 'رقم الدفعة',
    paymentCategory: 'فئة الدفعة',
    paymentStatus: 'حالة الدفعة',
    logout: 'تسجيل الخروج',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('eduverse-language');
      return (saved as Language) || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('eduverse-language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
