import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

// Comprehensive translations for the student dashboard
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    search: 'Search...',
    searchPlaceholder: 'Search courses, assignments, materials...',
    notifications: 'Notifications',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    viewProfile: 'View Profile',
    
    // Sidebar
    dashboard: 'Dashboard',
    myClass: 'My Class',
    registration: 'Registration',
    community: 'Community',
    schedule: 'Schedule',
    assignments: 'Assignments',
    labSessions: 'Lab Sessions',
    grades: 'Grades',
    attendance: 'Attendance',
    analytics: 'Analytics',
    todoList: 'Todo List',
    aiFeatures: 'AI Features',
    achievements: 'Achievements',
    payments: 'Payments',
    chat: 'Chat',
    settings: 'Settings',
    
    // Dashboard
    welcomeBack: 'Welcome back',
    semesterSummary: 'Semester Summary',
    currentGPA: 'Current GPA',
    completedCredits: 'Completed Credits',
    upcomingDeadlines: 'Upcoming Deadlines',
    todaySchedule: "Today's Schedule",
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',
    
    // StatsCard
    outOf: 'out of',
    hours: 'hours',
    totalCredits: 'Total Credits',
    pendingTasks: 'Pending Tasks',
    tasks: 'tasks',
    
    // DailySchedule
    noClassesToday: 'No classes scheduled for today',
    room: 'Room',
    
    // ClassTab / My Courses
    myCourses: 'My Courses',
    enrolled: 'Enrolled',
    viewCourse: 'View Course',
    courseCode: 'Course Code',
    instructor: 'Instructor',
    credits: 'Credits',
    progress: 'Progress',
    viewAll: 'View All',
    courseMaterials: 'Course Materials',
    
    // Course Registration
    courseRegistration: 'Course Registration',
    availableCourses: 'Available Courses',
    registeredCourses: 'Registered Courses',
    register: 'Register',
    drop: 'Drop',
    prerequisites: 'Prerequisites',
    seats: 'Seats',
    seatsAvailable: 'seats available',
    full: 'Full',
    waitlist: 'Waitlist',
    registrationSuccess: 'Successfully registered',
    dropSuccess: 'Course dropped successfully',
    springTerm: 'Spring Term',
    fallTerm: 'Fall Term',
    summerTerm: 'Summer Term',
    
    // Assignments
    assignmentsDue: 'Assignments Due',
    submitted: 'Submitted',
    pending: 'Pending',
    overdue: 'Overdue',
    dueDate: 'Due Date',
    submit: 'Submit',
    viewDetails: 'View Details',
    allAssignments: 'All Assignments',
    uploadFile: 'Upload File',
    submitAssignment: 'Submit Assignment',
    deadline: 'Deadline',
    status: 'Status',
    graded: 'Graded',
    notSubmitted: 'Not Submitted',
    lateSubmission: 'Late Submission',
    daysLeft: 'days left',
    hoursLeft: 'hours left',
    
    // Grades & Transcript
    gradeHistory: 'Grade History',
    transcript: 'Transcript',
    gpaChart: 'GPA Chart',
    semester: 'Semester',
    grade: 'Grade',
    cumulativeGPA: 'Cumulative GPA',
    semesterGPA: 'Semester GPA',
    creditHours: 'Credit Hours',
    gradePoints: 'Grade Points',
    course: 'Course',
    letterGrade: 'Letter Grade',
    downloadTranscript: 'Download Transcript',
    officialTranscript: 'Official Transcript',
    gradesAndTranscript: 'Grades & Transcript',
    academicRecord: 'Academic Record',
    
    // Attendance
    attendanceOverview: 'Attendance Overview',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    excused: 'Excused',
    attendanceRate: 'Attendance Rate',
    totalClasses: 'Total Classes',
    attended: 'Attended',
    missed: 'Missed',
    attendanceHistory: 'Attendance History',
    lectureAttendance: 'Lecture Attendance',
    labAttendance: 'Lab Attendance',
    warning: 'Warning',
    attendanceWarning: 'Your attendance is below the required minimum',
    overallAttendance: 'Overall Attendance',
    
    // Schedule
    weeklySchedule: 'Weekly Schedule',
    classSchedule: 'Class Schedule',
    today: 'Today',
    tomorrow: 'Tomorrow',
    thisWeek: 'This Week',
    noClasses: 'No classes scheduled',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sun: 'Sun',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    lecture: 'Lecture',
    lab: 'Lab',
    tutorial: 'Tutorial',
    exam: 'Exam',
    
    // AI Features
    aiAssistant: 'AI Assistant',
    aiPoweredTools: 'AI-Powered Learning Tools',
    summarizeNotes: 'Summarize Notes',
    generateQuiz: 'Generate Quiz',
    createFlashcards: 'Create Flashcards',
    studyRecommendations: 'Study Recommendations',
    voiceToText: 'Voice to Text',
    imageToText: 'Image to Text',
    aiChatbot: 'AI Chatbot',
    askQuestion: 'Ask a question...',
    generateSummary: 'Generate Summary',
    startQuiz: 'Start Quiz',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    numberOfQuestions: 'Number of Questions',
    flashcardDeck: 'Flashcard Deck',
    flip: 'Flip',
    correct: 'Correct',
    incorrect: 'Incorrect',
    noteSummarizer: 'Note Summarizer',
    quizGenerator: 'Quiz Generator',
    personalizedRecommendations: 'Personalized Recommendations',
    
    // Gamification
    points: 'Points',
    badges: 'Badges',
    leaderboard: 'Leaderboard',
    rank: 'Rank',
    earnedBadges: 'Earned Badges',
    totalPoints: 'Total Points',
    level: 'Level',
    xpToNextLevel: 'XP to Next Level',
    unlocked: 'Unlocked',
    locked: 'Locked',
    streak: 'Streak',
    daysStreak: 'Day Streak',
    weeklyGoal: 'Weekly Goal',
    challengeFriend: 'Challenge a Friend',
    yourRank: 'Your Rank',
    topStudents: 'Top Students',
    gamificationAchievements: 'Achievements & Rewards',
    
    // Community
    discussions: 'Discussions',
    announcements: 'Announcements',
    studyGroups: 'Study Groups',
    joinDiscussion: 'Join Discussion',
    postQuestion: 'Post a Question',
    newPost: 'New Post',
    reply: 'Reply',
    replies: 'Replies',
    like: 'Like',
    likes: 'Likes',
    share: 'Share',
    members: 'Members',
    joinGroup: 'Join Group',
    leaveGroup: 'Leave Group',
    createGroup: 'Create Group',
    groupName: 'Group Name',
    groupDescription: 'Group Description',
    courseCommunity: 'Course Community',
    
    // Labs
    labInstructions: 'Lab Instructions',
    labObjectives: 'Lab Objectives',
    resources: 'Resources',
    deliverables: 'Deliverables',
    submitDeliverable: 'Submit Deliverable',
    labReport: 'Lab Report',
    dueIn: 'Due in',
    labMaterials: 'Lab Materials',
    safetyGuidelines: 'Safety Guidelines',
    equipmentNeeded: 'Equipment Needed',
    procedure: 'Procedure',
    step: 'Step',
    labSession: 'Lab Session',
    
    // Analytics
    progressAnalytics: 'Progress & Analytics',
    studyHours: 'Study Hours',
    tasksCompleted: 'Tasks Completed',
    weakTopics: 'Topics to Review',
    strongTopics: 'Strong Topics',
    weeklyProgress: 'Weekly Progress',
    monthlyProgress: 'Monthly Progress',
    performanceTrend: 'Performance Trend',
    averageScore: 'Average Score',
    timeSpent: 'Time Spent',
    completionRate: 'Completion Rate',
    improvementAreas: 'Areas for Improvement',
    yourProgress: 'Your Progress',
    
    // Todo
    todoReminder: 'Todo & Reminders',
    addTask: 'Add Task',
    completed: 'Completed',
    inProgress: 'In Progress',
    priority: 'Priority',
    high: 'High',
    low: 'Low',
    taskTitle: 'Task Title',
    taskDescription: 'Task Description',
    setReminder: 'Set Reminder',
    reminderSet: 'Reminder Set',
    markComplete: 'Mark Complete',
    deleteTask: 'Delete Task',
    allTasks: 'All Tasks',
    todayTasks: "Today's Tasks",
    upcomingTasks: 'Upcoming Tasks',
    smartTodo: 'Smart Todo List',
    
    // Notifications
    allNotifications: 'All Notifications',
    unread: 'Unread',
    markAllRead: 'Mark All as Read',
    markAsRead: 'Mark as Read',
    notificationSettings: 'Notification Settings',
    noNotifications: 'No notifications',
    newNotification: 'New Notification',
    notificationCenter: 'Notification Center',
    
    // Chat / Messaging
    messages: 'Messages',
    sendMessage: 'Send Message',
    typeMessage: 'Type a message...',
    online: 'Online',
    offline: 'Offline',
    lastSeen: 'Last seen',
    newConversation: 'New Conversation',
    searchContacts: 'Search contacts...',
    noMessages: 'No messages yet',
    instructors: 'Instructors',
    classmates: 'Classmates',
    teachingAssistants: 'Teaching Assistants',
    messagingChat: 'Messaging',
    
    // Payments
    paymentHistory: 'Payment History',
    tuitionFees: 'Tuition & Fees',
    totalDue: 'Total Due',
    paid: 'Paid',
    unpaid: 'Unpaid',
    paymentDate: 'Payment Date',
    amount: 'Amount',
    paymentMethod: 'Payment Method',
    invoice: 'Invoice',
    downloadInvoice: 'Download Invoice',
    makePayment: 'Make Payment',
    paymentPlan: 'Payment Plan',
    financialAid: 'Financial Aid',
    scholarships: 'Scholarships',
    
    // Settings
    settingsPreferences: 'Settings & Preferences',
    customizeExperience: 'Customize your learning experience',
    appearance: 'Appearance',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    security: 'Security',
    twoFactorAuth: 'Two-Factor Authentication',
    twoFactorDesc: 'Add an extra layer of security to your account',
    enable2FA: 'Enable 2FA',
    disable2FA: 'Disable 2FA',
    privacy: 'Privacy',
    showOnlineStatus: 'Show Online Status',
    showActivityStatus: 'Show Activity Status',
    shareProgress: 'Share Progress with Classmates',
    accessibility: 'Accessibility',
    fontSize: 'Font Size',
    small: 'Small',
    large: 'Large',
    highContrast: 'High Contrast Mode',
    reduceMotion: 'Reduce Motion',
    offlineAccess: 'Offline Access',
    downloadMaterials: 'Download Materials',
    autoDownload: 'Auto-download Course Materials',
    wifiOnly: 'Download on Wi-Fi Only',
    storage: 'Storage',
    storageUsed: 'Used',
    clearCache: 'Clear Cache',
    downloadedItems: 'Downloaded Items',
    download: 'Download',
    remove: 'Remove',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    emailNotifications: 'Email Notifications',
    pushNotifications: 'Push Notifications',
    soundAlerts: 'Sound Alerts',
    deadlineReminders: 'Deadline Reminders',
    gradeUpdates: 'Grade Updates',
    
    // Global Search
    globalSearch: 'Global Search',
    searchResults: 'Search Results',
    recentSearches: 'Recent Searches',
    noResults: 'No results found',
    courses: 'Courses',
    files: 'Files',
    people: 'People',
    
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    seeAll: 'See All',
    noData: 'No data available',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    retry: 'Retry',
    refresh: 'Refresh',
    filter: 'Filter',
    sort: 'Sort',
    all: 'All',
    active: 'Active',
    inactive: 'Inactive',
    date: 'Date',
    time: 'Time',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    description: 'Description',
    details: 'Details',
    more: 'More',
    less: 'Less',
    showMore: 'Show More',
    showLess: 'Show Less',
    viewMore: 'View More',
  },
  ar: {
    // Header
    search: 'بحث...',
    searchPlaceholder: 'البحث عن المقررات والواجبات والمواد...',
    notifications: 'الإشعارات',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    viewProfile: 'عرض الملف الشخصي',
    
    // Sidebar
    dashboard: 'لوحة التحكم',
    myClass: 'صفي',
    registration: 'التسجيل',
    community: 'المجتمع',
    schedule: 'الجدول',
    assignments: 'الواجبات',
    labSessions: 'جلسات المعمل',
    grades: 'الدرجات',
    attendance: 'الحضور',
    analytics: 'التحليلات',
    todoList: 'قائمة المهام',
    aiFeatures: 'ميزات الذكاء الاصطناعي',
    achievements: 'الإنجازات',
    payments: 'المدفوعات',
    chat: 'المحادثة',
    settings: 'الإعدادات',
    
    // Dashboard
    welcomeBack: 'مرحباً بعودتك',
    semesterSummary: 'ملخص الفصل الدراسي',
    currentGPA: 'المعدل التراكمي الحالي',
    completedCredits: 'الساعات المكتملة',
    upcomingDeadlines: 'المواعيد النهائية القادمة',
    todaySchedule: 'جدول اليوم',
    quickActions: 'إجراءات سريعة',
    recentActivity: 'النشاط الأخير',
    
    // StatsCard
    outOf: 'من',
    hours: 'ساعات',
    totalCredits: 'إجمالي الساعات',
    pendingTasks: 'المهام المعلقة',
    tasks: 'مهام',
    
    // DailySchedule
    noClassesToday: 'لا توجد محاضرات مجدولة لليوم',
    room: 'القاعة',
    
    // ClassTab / My Courses
    myCourses: 'مقرراتي',
    enrolled: 'مسجل',
    viewCourse: 'عرض المقرر',
    courseCode: 'رمز المقرر',
    instructor: 'المحاضر',
    credits: 'الساعات',
    progress: 'التقدم',
    viewAll: 'عرض الكل',
    courseMaterials: 'مواد المقرر',
    
    // Course Registration
    courseRegistration: 'تسجيل المقررات',
    availableCourses: 'المقررات المتاحة',
    registeredCourses: 'المقررات المسجلة',
    register: 'تسجيل',
    drop: 'حذف',
    prerequisites: 'المتطلبات السابقة',
    seats: 'المقاعد',
    seatsAvailable: 'مقاعد متاحة',
    full: 'مكتمل',
    waitlist: 'قائمة الانتظار',
    registrationSuccess: 'تم التسجيل بنجاح',
    dropSuccess: 'تم حذف المقرر بنجاح',
    springTerm: 'الفصل الربيعي',
    fallTerm: 'الفصل الخريفي',
    summerTerm: 'الفصل الصيفي',
    
    // Assignments
    assignmentsDue: 'الواجبات المستحقة',
    submitted: 'تم التسليم',
    pending: 'قيد الانتظار',
    overdue: 'متأخر',
    dueDate: 'تاريخ التسليم',
    submit: 'تسليم',
    viewDetails: 'عرض التفاصيل',
    allAssignments: 'جميع الواجبات',
    uploadFile: 'رفع ملف',
    submitAssignment: 'تسليم الواجب',
    deadline: 'الموعد النهائي',
    status: 'الحالة',
    graded: 'تم التصحيح',
    notSubmitted: 'لم يتم التسليم',
    lateSubmission: 'تسليم متأخر',
    daysLeft: 'أيام متبقية',
    hoursLeft: 'ساعات متبقية',
    
    // Grades & Transcript
    gradeHistory: 'سجل الدرجات',
    transcript: 'السجل الأكاديمي',
    gpaChart: 'رسم المعدل التراكمي',
    semester: 'الفصل الدراسي',
    grade: 'الدرجة',
    cumulativeGPA: 'المعدل التراكمي',
    semesterGPA: 'معدل الفصل',
    creditHours: 'الساعات المعتمدة',
    gradePoints: 'نقاط الدرجات',
    course: 'المقرر',
    letterGrade: 'التقدير',
    downloadTranscript: 'تحميل السجل الأكاديمي',
    officialTranscript: 'السجل الأكاديمي الرسمي',
    gradesAndTranscript: 'الدرجات والسجل الأكاديمي',
    academicRecord: 'السجل الأكاديمي',
    
    // Attendance
    attendanceOverview: 'نظرة عامة على الحضور',
    present: 'حاضر',
    absent: 'غائب',
    late: 'متأخر',
    excused: 'معذور',
    attendanceRate: 'نسبة الحضور',
    totalClasses: 'إجمالي المحاضرات',
    attended: 'حضر',
    missed: 'فائت',
    attendanceHistory: 'سجل الحضور',
    lectureAttendance: 'حضور المحاضرات',
    labAttendance: 'حضور المعامل',
    warning: 'تحذير',
    attendanceWarning: 'نسبة حضورك أقل من الحد الأدنى المطلوب',
    overallAttendance: 'الحضور الإجمالي',
    
    // Schedule
    weeklySchedule: 'الجدول الأسبوعي',
    classSchedule: 'جدول المحاضرات',
    today: 'اليوم',
    tomorrow: 'غداً',
    thisWeek: 'هذا الأسبوع',
    noClasses: 'لا توجد محاضرات مجدولة',
    sunday: 'الأحد',
    monday: 'الاثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    saturday: 'السبت',
    sun: 'أحد',
    mon: 'اثنين',
    tue: 'ثلاثاء',
    wed: 'أربعاء',
    thu: 'خميس',
    fri: 'جمعة',
    sat: 'سبت',
    lecture: 'محاضرة',
    lab: 'معمل',
    tutorial: 'تدريب',
    exam: 'اختبار',
    
    // AI Features
    aiAssistant: 'مساعد الذكاء الاصطناعي',
    aiPoweredTools: 'أدوات التعلم بالذكاء الاصطناعي',
    summarizeNotes: 'تلخيص الملاحظات',
    generateQuiz: 'إنشاء اختبار',
    createFlashcards: 'إنشاء بطاقات تعليمية',
    studyRecommendations: 'توصيات الدراسة',
    voiceToText: 'تحويل الصوت إلى نص',
    imageToText: 'تحويل الصورة إلى نص',
    aiChatbot: 'روبوت المحادثة الذكي',
    askQuestion: 'اطرح سؤالاً...',
    generateSummary: 'إنشاء ملخص',
    startQuiz: 'بدء الاختبار',
    difficulty: 'الصعوبة',
    easy: 'سهل',
    medium: 'متوسط',
    hard: 'صعب',
    numberOfQuestions: 'عدد الأسئلة',
    flashcardDeck: 'مجموعة البطاقات',
    flip: 'قلب',
    correct: 'صحيح',
    incorrect: 'خطأ',
    noteSummarizer: 'ملخص الملاحظات',
    quizGenerator: 'منشئ الاختبارات',
    personalizedRecommendations: 'توصيات مخصصة',
    
    // Gamification
    points: 'النقاط',
    badges: 'الشارات',
    leaderboard: 'لوحة المتصدرين',
    rank: 'الترتيب',
    earnedBadges: 'الشارات المكتسبة',
    totalPoints: 'إجمالي النقاط',
    level: 'المستوى',
    xpToNextLevel: 'XP للمستوى التالي',
    unlocked: 'مفتوح',
    locked: 'مقفل',
    streak: 'السلسلة',
    daysStreak: 'أيام متتالية',
    weeklyGoal: 'الهدف الأسبوعي',
    challengeFriend: 'تحدي صديق',
    yourRank: 'ترتيبك',
    topStudents: 'أفضل الطلاب',
    gamificationAchievements: 'الإنجازات والمكافآت',
    
    // Community
    discussions: 'المناقشات',
    announcements: 'الإعلانات',
    studyGroups: 'مجموعات الدراسة',
    joinDiscussion: 'انضم للمناقشة',
    postQuestion: 'اطرح سؤالاً',
    newPost: 'منشور جديد',
    reply: 'رد',
    replies: 'الردود',
    like: 'إعجاب',
    likes: 'الإعجابات',
    share: 'مشاركة',
    members: 'الأعضاء',
    joinGroup: 'انضم للمجموعة',
    leaveGroup: 'مغادرة المجموعة',
    createGroup: 'إنشاء مجموعة',
    groupName: 'اسم المجموعة',
    groupDescription: 'وصف المجموعة',
    courseCommunity: 'مجتمع المقرر',
    
    // Labs
    labInstructions: 'تعليمات المعمل',
    labObjectives: 'أهداف المعمل',
    resources: 'الموارد',
    deliverables: 'المخرجات',
    submitDeliverable: 'تسليم المخرج',
    labReport: 'تقرير المعمل',
    dueIn: 'يستحق في',
    labMaterials: 'مواد المعمل',
    safetyGuidelines: 'إرشادات السلامة',
    equipmentNeeded: 'المعدات المطلوبة',
    procedure: 'الإجراءات',
    step: 'خطوة',
    labSession: 'جلسة المعمل',
    
    // Analytics
    progressAnalytics: 'التقدم والتحليلات',
    studyHours: 'ساعات الدراسة',
    tasksCompleted: 'المهام المكتملة',
    weakTopics: 'مواضيع تحتاج مراجعة',
    strongTopics: 'المواضيع القوية',
    weeklyProgress: 'التقدم الأسبوعي',
    monthlyProgress: 'التقدم الشهري',
    performanceTrend: 'اتجاه الأداء',
    averageScore: 'متوسط الدرجات',
    timeSpent: 'الوقت المستغرق',
    completionRate: 'نسبة الإنجاز',
    improvementAreas: 'مجالات التحسين',
    yourProgress: 'تقدمك',
    
    // Todo
    todoReminder: 'المهام والتذكيرات',
    addTask: 'إضافة مهمة',
    completed: 'مكتمل',
    inProgress: 'قيد التنفيذ',
    priority: 'الأولوية',
    high: 'عالية',
    low: 'منخفضة',
    taskTitle: 'عنوان المهمة',
    taskDescription: 'وصف المهمة',
    setReminder: 'تعيين تذكير',
    reminderSet: 'تم تعيين التذكير',
    markComplete: 'تحديد كمكتمل',
    deleteTask: 'حذف المهمة',
    allTasks: 'جميع المهام',
    todayTasks: 'مهام اليوم',
    upcomingTasks: 'المهام القادمة',
    smartTodo: 'قائمة المهام الذكية',
    
    // Notifications
    allNotifications: 'جميع الإشعارات',
    unread: 'غير مقروء',
    markAllRead: 'تحديد الكل كمقروء',
    markAsRead: 'تحديد كمقروء',
    notificationSettings: 'إعدادات الإشعارات',
    noNotifications: 'لا توجد إشعارات',
    newNotification: 'إشعار جديد',
    notificationCenter: 'مركز الإشعارات',
    
    // Chat / Messaging
    messages: 'الرسائل',
    sendMessage: 'إرسال رسالة',
    typeMessage: 'اكتب رسالة...',
    online: 'متصل',
    offline: 'غير متصل',
    lastSeen: 'آخر ظهور',
    newConversation: 'محادثة جديدة',
    searchContacts: 'البحث في جهات الاتصال...',
    noMessages: 'لا توجد رسائل بعد',
    instructors: 'المحاضرون',
    classmates: 'زملاء الدراسة',
    teachingAssistants: 'المعيدون',
    messagingChat: 'المراسلة',
    
    // Payments
    paymentHistory: 'سجل المدفوعات',
    tuitionFees: 'الرسوم الدراسية',
    totalDue: 'إجمالي المستحق',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    paymentDate: 'تاريخ الدفع',
    amount: 'المبلغ',
    paymentMethod: 'طريقة الدفع',
    invoice: 'الفاتورة',
    downloadInvoice: 'تحميل الفاتورة',
    makePayment: 'إجراء دفعة',
    paymentPlan: 'خطة الدفع',
    financialAid: 'المساعدة المالية',
    scholarships: 'المنح الدراسية',
    
    // Settings
    settingsPreferences: 'الإعدادات والتفضيلات',
    customizeExperience: 'خصص تجربة التعلم الخاصة بك',
    appearance: 'المظهر',
    theme: 'السمة',
    light: 'فاتح',
    dark: 'داكن',
    system: 'النظام',
    security: 'الأمان',
    twoFactorAuth: 'المصادقة الثنائية',
    twoFactorDesc: 'أضف طبقة إضافية من الأمان لحسابك',
    enable2FA: 'تفعيل المصادقة الثنائية',
    disable2FA: 'إلغاء المصادقة الثنائية',
    privacy: 'الخصوصية',
    showOnlineStatus: 'إظهار حالة الاتصال',
    showActivityStatus: 'إظهار حالة النشاط',
    shareProgress: 'مشاركة التقدم مع زملاء الدراسة',
    accessibility: 'إمكانية الوصول',
    fontSize: 'حجم الخط',
    small: 'صغير',
    large: 'كبير',
    highContrast: 'وضع التباين العالي',
    reduceMotion: 'تقليل الحركة',
    offlineAccess: 'الوصول دون اتصال',
    downloadMaterials: 'تحميل المواد',
    autoDownload: 'تنزيل مواد الدورة تلقائياً',
    wifiOnly: 'التنزيل عبر Wi-Fi فقط',
    storage: 'التخزين',
    storageUsed: 'مستخدم',
    clearCache: 'مسح ذاكرة التخزين المؤقت',
    downloadedItems: 'العناصر المحملة',
    download: 'تنزيل',
    remove: 'إزالة',
    saveChanges: 'حفظ التغييرات',
    cancel: 'إلغاء',
    emailNotifications: 'إشعارات البريد الإلكتروني',
    pushNotifications: 'الإشعارات الفورية',
    soundAlerts: 'تنبيهات صوتية',
    deadlineReminders: 'تذكيرات المواعيد النهائية',
    gradeUpdates: 'تحديثات الدرجات',
    
    // Global Search
    globalSearch: 'البحث الشامل',
    searchResults: 'نتائج البحث',
    recentSearches: 'عمليات البحث الأخيرة',
    noResults: 'لا توجد نتائج',
    courses: 'المقررات',
    files: 'الملفات',
    people: 'الأشخاص',
    
    // Common
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجاح',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    close: 'إغلاق',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    seeAll: 'عرض الكل',
    noData: 'لا توجد بيانات',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    ok: 'موافق',
    retry: 'إعادة المحاولة',
    refresh: 'تحديث',
    filter: 'تصفية',
    sort: 'ترتيب',
    all: 'الكل',
    active: 'نشط',
    inactive: 'غير نشط',
    date: 'التاريخ',
    time: 'الوقت',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    description: 'الوصف',
    details: 'التفاصيل',
    more: 'المزيد',
    less: 'أقل',
    showMore: 'عرض المزيد',
    showLess: 'عرض أقل',
    viewMore: 'عرض المزيد',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('eduverse-language');
      return (saved as Language) || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('eduverse-language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
