import {
  FileText,
  Brain,
  MessageSquare,
  Mic,
  Lightbulb,
  Image as ImageIcon,
} from 'lucide-react';
import { AIFeature } from './types';

export const aiFeatures: AIFeature[] = [
  {
    id: 'summarizer',
    title: 'Smart Summarizer',
    subtitle: 'Intelligent Content Condensing',
    description: 'Transform lengthy documents, research papers, and lecture notes into concise, actionable summaries in seconds',
    icon: FileText,
    color: 'bg-blue-600',
    bgLight: 'bg-blue-50',
    bgHover: 'hover:bg-blue-100',
    textColor: 'text-blue-700',
    borderColor: 'border-blue-500',
    usageCount: 45,
    lastUsed: '2 hours ago',
    features: ['PDF & DOCX Support', 'Key Points Extraction', 'Smart Highlighting'],
    badge: 'Popular'
  },
  {
    id: 'quiz',
    title: 'Quiz Generator',
    subtitle: 'Adaptive Learning Assessment',
    description: 'Create personalized quizzes with AI-powered difficulty adjustment to match your learning pace and knowledge level',
    icon: Brain,
    color: 'bg-purple-600',
    bgLight: 'bg-purple-50',
    bgHover: 'hover:bg-purple-100',
    textColor: 'text-purple-700',
    borderColor: 'border-purple-500',
    usageCount: 28,
    lastUsed: '1 day ago',
    features: ['Adaptive Difficulty', 'Instant Grading', 'Performance Analytics'],
    badge: 'New'
  },
  {
    id: 'feedback',
    title: 'Writing Assistant',
    subtitle: 'Professional Feedback Engine',
    description: 'Receive comprehensive, constructive feedback on your assignments with advanced grammar, style, and clarity analysis',
    icon: MessageSquare,
    color: 'bg-emerald-600',
    bgLight: 'bg-emerald-50',
    bgHover: 'hover:bg-emerald-100',
    textColor: 'text-emerald-700',
    borderColor: 'border-emerald-500',
    usageCount: 32,
    lastUsed: '3 hours ago',
    features: ['Grammar Check', 'Style Enhancement', 'Plagiarism Detection']
  },
  {
    id: 'chatbot',
    title: 'Study Companion',
    subtitle: '24/7 AI Learning Assistant',
    description: 'Get instant, intelligent answers to your academic questions with context-aware responses tailored to your courses',
    icon: MessageSquare,
    color: 'bg-indigo-600',
    bgLight: 'bg-indigo-50',
    bgHover: 'hover:bg-indigo-100',
    textColor: 'text-indigo-700',
    borderColor: 'border-indigo-500',
    usageCount: 156,
    lastUsed: '10 minutes ago',
    features: ['24/7 Availability', 'Multi-Subject Support', 'Context Memory'],
    badge: 'Most Used'
  },
  {
    id: 'voice',
    title: 'Voice Transcriber',
    subtitle: 'Smart Audio to Text',
    description: 'Convert lectures, meetings, and voice notes into accurate, searchable text with automatic timestamp marking',
    icon: Mic,
    color: 'bg-pink-600',
    bgLight: 'bg-pink-50',
    bgHover: 'hover:bg-pink-100',
    textColor: 'text-pink-700',
    borderColor: 'border-pink-500',
    usageCount: 67,
    lastUsed: '5 hours ago',
    features: ['Real-time Processing', 'Multi-language', 'Speaker Detection']
  },
  {
    id: 'recommendation',
    title: 'Smart Recommender',
    subtitle: 'Personalized Learning Path',
    description: 'Discover curated study materials, courses, and resources powered by your unique learning patterns and goals',
    icon: Lightbulb,
    color: 'bg-amber-600',
    bgLight: 'bg-amber-50',
    bgHover: 'hover:bg-amber-100',
    textColor: 'text-amber-700',
    borderColor: 'border-amber-500',
    usageCount: 89,
    lastUsed: '1 hour ago',
    features: ['AI Matching', 'Progress Tracking', 'Resource Library']
  },
  {
    id: 'image-to-text',
    title: 'OCR Scanner',
    subtitle: 'Visual Text Extraction',
    description: 'Instantly extract and digitize text from images, diagrams, handwritten notes, and scanned documents',
    icon: ImageIcon,
    color: 'bg-teal-600',
    bgLight: 'bg-teal-50',
    bgHover: 'hover:bg-teal-100',
    textColor: 'text-teal-700',
    borderColor: 'border-teal-500',
    usageCount: 23,
    lastUsed: '2 days ago',
    features: ['Handwriting Support', 'Multi-format', 'Batch Processing']
  }
];
