import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    search: 'Search...',
    searchPlaceholder: 'Search users, courses, departments...',
    notifications: 'Notifications',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    viewProfile: 'View Profile',
    logout: 'Logout',
    dashboard: 'Dashboard',
    adminDashboard: 'Admin Dashboard',
    userManagement: 'User Management',
    courseManagement: 'Course Management',
    departmentManagement: 'Department Management',
    academicCalendar: 'Academic Calendar',
    analytics: 'Analytics & Reports',
    communication: 'Communication',
    feedback: 'Feedback & Support',
    systemConfig: 'System Configuration',
    settings: 'Settings',
    welcomeBack: 'Welcome back',
    overviewDescription: 'Manage your platform, monitor system health, and configure settings.',
    systemHealth: 'System Health',
    platformStatus: 'Platform Status',
    totalUsers: 'Total Users',
    activeUsers: 'Active Users',
    totalCourses: 'Total Courses',
    activeCourses: 'Active Courses',
    totalDepartments: 'Departments',
    systemUptime: 'System Uptime',
    pendingRequests: 'Pending Requests',
    users: 'Users',
    addUser: 'Add User',
    editUser: 'Edit User',
    deleteUser: 'Delete User',
    userName: 'User Name',
    email: 'Email',
    role: 'Role',
    status: 'Status',
    lastActive: 'Last Active',
    student: 'Student',
    instructor: 'Instructor',
    ta: 'Teaching Assistant',
    admin: 'Admin',
    active: 'Active',
    inactive: 'Inactive',
    suspended: 'Suspended',
    assignRole: 'Assign Role',
    permissions: 'Permissions',
    courses: 'Courses',
    addCourse: 'Add Course',
    editCourse: 'Edit Course',
    deleteCourse: 'Delete Course',
    courseCode: 'Course Code',
    courseName: 'Course Name',
    department: 'Department',
    semester: 'Semester',
    credits: 'Credits',
    enrolled: 'Enrolled',
    capacity: 'Capacity',
    departments: 'Departments',
    addDepartment: 'Add Department',
    editDepartment: 'Edit Department',
    deleteDepartment: 'Delete Department',
    departmentName: 'Department Name',
    faculty: 'Faculty',
    headOfDepartment: 'Head of Department',
    coursesCount: 'Courses Count',
    studentsCount: 'Students Count',
    instructorsCount: 'Instructors Count',
    calendar: 'Calendar',
    addEvent: 'Add Event',
    editEvent: 'Edit Event',
    deleteEvent: 'Delete Event',
    eventTitle: 'Event Title',
    eventDate: 'Event Date',
    eventType: 'Event Type',
    holiday: 'Holiday',
    examPeriod: 'Exam Period',
    semesterStart: 'Semester Start',
    semesterEnd: 'Semester End',
    registrationPeriod: 'Registration Period',
    systemAnalytics: 'System Analytics',
    userStatistics: 'User Statistics',
    courseStatistics: 'Course Statistics',
    engagementMetrics: 'Engagement Metrics',
    aiUsageStats: 'AI Feature Usage',
    exportData: 'Export Data',
    exportPDF: 'Export PDF',
    exportExcel: 'Export Excel',
    generateReport: 'Generate Report',
    broadcastNotification: 'Broadcast Notification',
    sendToAll: 'Send to All Users',
    sendToStudents: 'Send to Students',
    sendToInstructors: 'Send to Instructors',
    notificationTemplates: 'Notification Templates',
    createTemplate: 'Create Template',
    editTemplate: 'Edit Template',
    userFeedback: 'User Feedback',
    supportTickets: 'Support Tickets',
    resolved: 'Resolved',
    pending: 'Pending',
    inProgress: 'In Progress',
    priority: 'Priority',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    auditLogs: 'Audit Logs',
    gamificationSettings: 'Gamification Settings',
    apiIntegrations: 'API Integrations',
    enablePoints: 'Enable Points System',
    enableBadges: 'Enable Badges',
    enableLeaderboards: 'Enable Leaderboards',
    moodleIntegration: 'Moodle Integration',
    blackboardIntegration: 'Blackboard Integration',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    submit: 'Submit',
    apply: 'Apply',
    reset: 'Reset',
    filter: 'Filter',
    sort: 'Sort',
    noData: 'No data available',
    viewAll: 'View All',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    download: 'Download',
    upload: 'Upload',
    export: 'Export',
    import: 'Import',
    refresh: 'Refresh',
    date: 'Date',
    time: 'Time',
    actions: 'Actions',
    more: 'More',
    // Dashboard Overview
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    manageUsers: 'Manage Users',
    manageCourses: 'Manage Courses',
    viewAnalytics: 'View Analytics',
    systemSettings: 'System Settings',
    enrollmentTrends: 'Enrollment Trends',
    activeUsersChart: 'Active Users',
    allOperational: 'All systems operational',
    viewDetails: 'View Details',
    platformHealthDashboard: 'Platform Health Dashboard',
    monitorPerformance:
      'Monitor real-time system performance, user activity, and AI feature usage across the platform.',
    userGrowthTrend: 'User Growth Trend',
    userDistribution: 'User Distribution',
    sendBroadcast: 'Send Broadcast',
    requestsThisMonth: 'requests this month',
    // Course Management
    searchCourses: 'Search courses...',
    allDepartments: 'All Departments',
    allSemesters: 'All Semesters',
    courseTitle: 'Course Title',
    courseInstructor: 'Instructor',
    courseStudents: 'Students',
    openEnrollment: 'Open Enrollment',
    closedEnrollment: 'Closed Enrollment',
    saveCourse: 'Save Course',
    addNewCourse: 'Add New Course',
    manageCoursesSub: 'Manage all courses across departments',
    enrollment: 'Enrollment',
    allStatus: 'All Status',
    archived: 'Archived',
    // Department Management
    totalFaculty: 'Total Faculty',
    totalStudentsInDept: 'Total Students',
    manageDepartments: 'Manage Departments',
    deptPrograms: 'Programs',
    deptBudget: 'Budget',
    addNewDepartment: 'Add New Department',
    manageDeptSub: 'Manage academic departments and their structure',
    totalInstructors: 'Total Instructors',
    allFaculties: 'All Faculties',
    searchDepartments: 'Search departments...',
    head: 'Head',
    students: 'Students',
    // Academic Calendar
    academicCalendarTitle: 'Academic Calendar',
    addNewEvent: 'Add New Event',
    thisMonth: 'This Month',
    upcoming: 'Upcoming',
    past: 'Past',
    allEvents: 'All Events',
    eventDescription: 'Description',
    startDate: 'Start Date',
    endDate: 'End Date',
    manageCalendarSub: 'Manage academic events, holidays, and important dates',
    eventTypes: 'Event Types',
    monthView: 'Month',
    listView: 'List',
    allEventTypes: 'All Event Types',
    registration: 'Registration',
    endDateOptional: 'End Date (Optional)',
    // Analytics & Reports
    reportsOverview: 'Reports Overview',
    totalRevenue: 'Total Revenue',
    completionRate: 'Completion Rate',
    avgGrade: 'Average Grade',
    userGrowth: 'User Growth',
    courseEnrollment: 'Course Enrollment',
    timeRange: 'Time Range',
    lastMonth: 'Last Month',
    lastQuarter: 'Last Quarter',
    lastYear: 'Last Year',
    systemWideAnalytics: 'System-wide analytics and reports',
    lastWeek: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    last3Months: 'Last 3 Months',
    userAnalytics: 'User Analytics',
    courseAnalytics: 'Course Analytics',
    engagement: 'Engagement',
    aiUsage: 'AI Usage',
    coursePerformance: 'Course Performance',
    engagementByCourse: 'Engagement by Course',
    weeklyEngagement: 'Weekly Engagement',
    activeTodayLabel: 'Active Today',
    newThisMonth: 'New This Month',
    inactiveUsers: 'Inactive Users',
    attendance: 'Attendance',
    course: 'Course',
    // Communication
    sendMessage: 'Send Message',
    composeMessage: 'Compose Message',
    recipients: 'Recipients',
    messageBody: 'Message',
    messageSubject: 'Subject',
    sent: 'Sent',
    drafts: 'Drafts',
    inbox: 'Inbox',
    selectAll: 'Select All',
    composeBroadcast: 'Compose Broadcast',
    sendBroadcastsSub: 'Send broadcasts and manage notification templates',
    title: 'Title',
    targetAudience: 'Target Audience',
    notificationChannels: 'Notification Channels',
    sendTime: 'Send Time',
    sendNow: 'Send Now',
    scheduleSend: 'Schedule',
    preview: 'Preview',
    recentBroadcasts: 'Recent Broadcasts',
    notificationPreview: 'Notification Preview',
    templateName: 'Template Name',
    type: 'Type',
    content: 'Content',
    allUsersAudience: 'All Users',
    studentsOnly: 'Students Only',
    instructorsOnly: 'Instructors Only',
    adminsOnly: 'Admins Only',
    // Feedback & Support
    openTickets: 'Open Tickets',
    avgResponseTime: 'Avg Response Time',
    satisfactionRate: 'Satisfaction Rate',
    ticketId: 'Ticket ID',
    assignedTo: 'Assigned To',
    respondToTicket: 'Respond',
    closeTicket: 'Close Ticket',
    escalateTicket: 'Escalate',
    totalTickets: 'Total Tickets',
    manageFeedbackSub: 'Manage user feedback, reports, and support tickets',
    searchTickets: 'Search tickets...',
    allPriorities: 'All Priorities',
    updateStatus: 'Update Status',
    reply: 'Reply',
    sendReply: 'Send Reply',
    // System Configuration
    generalSettings: 'General Settings',
    securitySettings: 'Security Settings',
    emailSettings: 'Email Settings',
    backupSettings: 'Backup Settings',
    platformName: 'Platform Name',
    platformUrl: 'Platform URL',
    maintenanceMode: 'Maintenance Mode',
    autoBackup: 'Auto Backup',
    backupFrequency: 'Backup Frequency',
    smtpServer: 'SMTP Server',
    enableTwoFactor: 'Two-Factor Authentication',
    passwordPolicy: 'Password Policy',
    manageSystemSub: 'Manage system settings, integrations, and audit logs',
    featureToggles: 'Feature Toggles',
    pointsConfiguration: 'Points Configuration',
    badgesLabel: 'Badges',
    saveChanges: 'Save Changes',
    searchLogs: 'Search logs...',
    allActions: 'All Actions',
    userActionsFilter: 'User Actions',
    courseActionsFilter: 'Course Actions',
    systemActionsFilter: 'System Actions',
    exportLogs: 'Export Logs',
    timestamp: 'Timestamp',
    action: 'Action',
    user: 'User',
    target: 'Target',
    ipAddress: 'IP Address',
    lastSync: 'Last Sync',
    syncFrequencyLabel: 'Sync Frequency',
    dataTypes: 'Data Types',
    syncNow: 'Sync Now',
    notConnected: 'Not connected',
    configureConnection: 'Configure Connection',
    awardPointsDesc: 'Award points for various activities',
    enableBadgesDesc: 'Enable achievement badges for students',
    showLeaderboardsDesc: 'Show public leaderboards',
    // Schedule Management
    scheduleManagement: 'Schedule Management',
    manageScheduleSub: 'Create and manage class schedules for your department',
    addSchedule: 'Add Schedule',
    editSchedule: 'Edit Schedule',
    deleteSchedule: 'Delete Schedule',
    day: 'Day',
    startTime: 'Start Time',
    endTime: 'End Time',
    room: 'Room',
    scheduleType: 'Type',
    lecture: 'Lecture',
    lab: 'Lab',
    section: 'Section',
    tutorial: 'Tutorial',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    saturday: 'Saturday',
    conflictWarning: 'Schedule conflict detected!',
    noSchedules: 'No schedules created yet',
    weeklyView: 'Weekly View',
    totalSessions: 'Total Sessions',
    totalRooms: 'Rooms Used',
    searchSchedules: 'Search schedules...',
    allDays: 'All Days',
    allTypes: 'All Types',
    // Exam Schedule
    examSchedule: 'Exam Schedule',
    manageExamsSub: 'Schedule and manage exams for your department courses',
    addExam: 'Add Exam',
    editExam: 'Edit Exam',
    deleteExam: 'Delete Exam',
    examType: 'Exam Type',
    midterm: 'Midterm',
    final: 'Final',
    quiz: 'Quiz',
    practical: 'Practical',
    duration: 'Duration (min)',
    examDate: 'Exam Date',
    noExams: 'No exams scheduled yet',
    searchExams: 'Search exams...',
    allExamTypes: 'All Exam Types',
    totalExams: 'Total Exams',
    upcomingExams: 'Upcoming Exams',
    // Enrollment Periods
    enrollmentPeriods: 'Enrollment Periods',
    manageEnrollmentSub: 'Open and manage enrollment periods for your department courses',
    addEnrollmentPeriod: 'Add Period',
    editEnrollmentPeriod: 'Edit Period',
    deleteEnrollmentPeriod: 'Delete Period',
    waitlist: 'Waitlist',
    waitlistCapacity: 'Waitlist Capacity',
    waitlistEnabled: 'Waitlist Enabled',
    enrollmentStatus: 'Status',
    activePeriod: 'Active',
    closedPeriod: 'Closed',
    upcomingPeriod: 'Upcoming',
    noEnrollmentPeriods: 'No enrollment periods created yet',
    searchEnrollment: 'Search enrollment periods...',
    totalPeriods: 'Total Periods',
    activePeriods: 'Active Periods',
    openEnrollmentPeriod: 'Open Period',
    // Prerequisites Management
    prerequisitesManagement: 'Prerequisites',
    managePrereqSub: 'Set and manage course prerequisites for your department',
    addPrerequisite: 'Add Prerequisite',
    removePrerequisite: 'Remove',
    prerequisitesFor: 'Prerequisites for',
    noPrerequisites: 'No prerequisites set',
    availableCourses: 'Available Courses',
    currentPrerequisites: 'Current Prerequisites',
    prerequisiteChain: 'Prerequisite Chain',
    searchPrerequisites: 'Search courses...',
    selectCourse: 'Select Course',
    selectInstructor: 'Select Instructor',
    selectTA: 'Select TA',
    assignedTAs: 'Assigned TAs',
    assignInstructor: 'Assign Instructor',
    assignTA: 'Assign TA',
    departmentScope: 'Department Scope',
    yourDepartment: 'Your Department',
    courseAdded: 'Course created successfully',
    courseUpdated: 'Course updated successfully',
    courseDeleted: 'Course deleted successfully',
    staffAssignment: 'Staff Assignment',
    assign: 'Assign',
    staffAssignmentTab: 'Staff Assignment',
    scheduleTab: 'Schedule',
    examsTab: 'Exam Schedule',
    coursesTab: 'Courses',
    unassigned: 'Unassigned',
    none: 'None',
    classSchedule: 'Class Schedule',
    examScheduleTitle: 'Exam Schedule',
  },
  ar: {
    search: 'بحث...',
    searchPlaceholder: 'البحث عن المستخدمين والمقررات والأقسام...',
    notifications: 'الإشعارات',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    viewProfile: 'عرض الملف الشخصي',
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    adminDashboard: 'لوحة تحكم المدير',
    userManagement: 'إدارة المستخدمين',
    courseManagement: 'إدارة المقررات',
    departmentManagement: 'إدارة الأقسام',
    academicCalendar: 'التقويم الأكاديمي',
    analytics: 'التحليلات والتقارير',
    communication: 'التواصل',
    feedback: 'الملاحظات والدعم',
    systemConfig: 'إعدادات النظام',
    settings: 'الإعدادات',
    welcomeBack: 'مرحباً بعودتك',
    overviewDescription: 'إدارة المنصة ومراقبة صحة النظام وتكوين الإعدادات.',
    systemHealth: 'صحة النظام',
    platformStatus: 'حالة المنصة',
    totalUsers: 'إجمالي المستخدمين',
    activeUsers: 'المستخدمون النشطون',
    totalCourses: 'إجمالي المقررات',
    activeCourses: 'المقررات النشطة',
    totalDepartments: 'الأقسام',
    systemUptime: 'وقت تشغيل النظام',
    pendingRequests: 'الطلبات المعلقة',
    users: 'المستخدمون',
    addUser: 'إضافة مستخدم',
    editUser: 'تعديل مستخدم',
    deleteUser: 'حذف مستخدم',
    userName: 'اسم المستخدم',
    email: 'البريد الإلكتروني',
    role: 'الدور',
    status: 'الحالة',
    lastActive: 'آخر نشاط',
    student: 'طالب',
    instructor: 'محاضر',
    ta: 'معيد',
    admin: 'مدير',
    active: 'نشط',
    inactive: 'غير نشط',
    suspended: 'معلق',
    assignRole: 'تعيين دور',
    permissions: 'الصلاحيات',
    courses: 'المقررات',
    addCourse: 'إضافة مقرر',
    editCourse: 'تعديل مقرر',
    deleteCourse: 'حذف مقرر',
    courseCode: 'رمز المقرر',
    courseName: 'اسم المقرر',
    department: 'القسم',
    semester: 'الفصل الدراسي',
    credits: 'الساعات المعتمدة',
    enrolled: 'المسجلين',
    capacity: 'السعة',
    departments: 'الأقسام',
    addDepartment: 'إضافة قسم',
    editDepartment: 'تعديل قسم',
    deleteDepartment: 'حذف قسم',
    departmentName: 'اسم القسم',
    faculty: 'الكلية',
    headOfDepartment: 'رئيس القسم',
    coursesCount: 'عدد المقررات',
    studentsCount: 'عدد الطلاب',
    instructorsCount: 'عدد المحاضرين',
    calendar: 'التقويم',
    addEvent: 'إضافة حدث',
    editEvent: 'تعديل حدث',
    deleteEvent: 'حذف حدث',
    eventTitle: 'عنوان الحدث',
    eventDate: 'تاريخ الحدث',
    eventType: 'نوع الحدث',
    holiday: 'عطلة',
    examPeriod: 'فترة الامتحانات',
    semesterStart: 'بداية الفصل',
    semesterEnd: 'نهاية الفصل',
    registrationPeriod: 'فترة التسجيل',
    systemAnalytics: 'تحليلات النظام',
    userStatistics: 'إحصائيات المستخدمين',
    courseStatistics: 'إحصائيات المقررات',
    engagementMetrics: 'مقاييس المشاركة',
    aiUsageStats: 'استخدام ميزات الذكاء الاصطناعي',
    exportData: 'تصدير البيانات',
    exportPDF: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    generateReport: 'إنشاء تقرير',
    broadcastNotification: 'إشعار عام',
    sendToAll: 'إرسال للجميع',
    sendToStudents: 'إرسال للطلاب',
    sendToInstructors: 'إرسال للمحاضرين',
    notificationTemplates: 'قوالب الإشعارات',
    createTemplate: 'إنشاء قالب',
    editTemplate: 'تعديل قالب',
    userFeedback: 'ملاحظات المستخدمين',
    supportTickets: 'تذاكر الدعم',
    resolved: 'تم الحل',
    pending: 'معلق',
    inProgress: 'قيد المعالجة',
    priority: 'الأولوية',
    high: 'عالية',
    medium: 'متوسطة',
    low: 'منخفضة',
    auditLogs: 'سجلات المراجعة',
    gamificationSettings: 'إعدادات اللعبة',
    apiIntegrations: 'تكاملات API',
    enablePoints: 'تفعيل نظام النقاط',
    enableBadges: 'تفعيل الشارات',
    enableLeaderboards: 'تفعيل لوحات الصدارة',
    moodleIntegration: 'تكامل Moodle',
    blackboardIntegration: 'تكامل Blackboard',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجاح',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    close: 'إغلاق',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    submit: 'إرسال',
    apply: 'تطبيق',
    reset: 'إعادة تعيين',
    filter: 'تصفية',
    sort: 'ترتيب',
    noData: 'لا توجد بيانات',
    viewAll: 'عرض الكل',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    download: 'تنزيل',
    upload: 'رفع',
    export: 'تصدير',
    import: 'استيراد',
    refresh: 'تحديث',
    date: 'التاريخ',
    time: 'الوقت',
    actions: 'الإجراءات',
    more: 'المزيد',
    // Dashboard Overview
    recentActivity: 'النشاط الأخير',
    quickActions: 'إجراءات سريعة',
    manageUsers: 'إدارة المستخدمين',
    manageCourses: 'إدارة المقررات',
    viewAnalytics: 'عرض التحليلات',
    systemSettings: 'إعدادات النظام',
    enrollmentTrends: 'اتجاهات التسجيل',
    activeUsersChart: 'المستخدمون النشطون',
    allOperational: 'كل شيء يعمل',
    viewDetails: 'عرض التفاصيل',
    platformHealthDashboard: 'لوحة صحة المنصة',
    monitorPerformance:
      'مراقبة أداء النظام في الوقت الفعلي ونشاط المستخدمين واستخدام ميزات الذكاء الاصطناعي عبر المنصة.',
    userGrowthTrend: 'اتجاه نمو المستخدمين',
    userDistribution: 'توزيع المستخدمين',
    sendBroadcast: 'إرسال بث',
    requestsThisMonth: 'طلب هذا الشهر',
    // Course Management
    searchCourses: 'البحث عن المقررات...',
    allDepartments: 'جميع الأقسام',
    allSemesters: 'جميع الفصول',
    courseTitle: 'عنوان المقرر',
    courseInstructor: 'المحاضر',
    courseStudents: 'الطلاب',
    openEnrollment: 'التسجيل مفتوح',
    closedEnrollment: 'التسجيل مغلق',
    saveCourse: 'حفظ المقرر',
    addNewCourse: 'إضافة مقرر جديد',
    manageCoursesSub: 'إدارة جميع المقررات عبر الأقسام',
    enrollment: 'التسجيل',
    allStatus: 'جميع الحالات',
    archived: 'مؤرشف',
    // Department Management
    totalFaculty: 'إجمالي أعضاء هيئة التدريس',
    totalStudentsInDept: 'إجمالي الطلاب',
    manageDepartments: 'إدارة الأقسام',
    deptPrograms: 'البرامج',
    deptBudget: 'الميزانية',
    addNewDepartment: 'إضافة قسم جديد',
    manageDeptSub: 'إدارة الأقسام الأكاديمية وهيكلها',
    totalInstructors: 'إجمالي المحاضرين',
    allFaculties: 'جميع الكليات',
    searchDepartments: 'البحث عن الأقسام...',
    head: 'الرئيس',
    students: 'الطلاب',
    // Academic Calendar
    academicCalendarTitle: 'التقويم الأكاديمي',
    addNewEvent: 'إضافة حدث جديد',
    thisMonth: 'هذا الشهر',
    upcoming: 'القادم',
    past: 'الماضي',
    allEvents: 'جميع الأحداث',
    eventDescription: 'الوصف',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    manageCalendarSub: 'إدارة الأحداث الأكاديمية والعطلات والتواريخ المهمة',
    eventTypes: 'أنواع الأحداث',
    monthView: 'شهر',
    listView: 'قائمة',
    allEventTypes: 'جميع أنواع الأحداث',
    registration: 'التسجيل',
    endDateOptional: 'تاريخ النهاية (اختياري)',
    // Analytics & Reports
    reportsOverview: 'نظرة عامة على التقارير',
    totalRevenue: 'إجمالي الإيرادات',
    completionRate: 'معدل الإكمال',
    avgGrade: 'متوسط الدرجات',
    userGrowth: 'نمو المستخدمين',
    courseEnrollment: 'تسجيل المقررات',
    timeRange: 'النطاق الزمني',
    lastMonth: 'الشهر الماضي',
    lastQuarter: 'الربع الماضي',
    lastYear: 'السنة الماضية',
    systemWideAnalytics: 'التحليلات والتقارير على مستوى النظام',
    lastWeek: 'آخر ٧ أيام',
    last30Days: 'آخر ٣٠ يوم',
    last3Months: 'آخر ٣ أشهر',
    userAnalytics: 'تحليلات المستخدمين',
    courseAnalytics: 'تحليلات المقررات',
    engagement: 'التفاعل',
    aiUsage: 'استخدام الذكاء الاصطناعي',
    coursePerformance: 'أداء المقررات',
    engagementByCourse: 'التفاعل حسب المقرر',
    weeklyEngagement: 'التفاعل الأسبوعي',
    activeTodayLabel: 'نشط اليوم',
    newThisMonth: 'جديد هذا الشهر',
    inactiveUsers: 'المستخدمون غير النشطين',
    attendance: 'الحضور',
    course: 'المقرر',
    // Communication
    sendMessage: 'إرسال رسالة',
    composeMessage: 'إنشاء رسالة',
    recipients: 'المستلمون',
    messageBody: 'الرسالة',
    messageSubject: 'الموضوع',
    sent: 'المرسل',
    drafts: 'المسودات',
    inbox: 'الوارد',
    selectAll: 'تحديد الكل',
    composeBroadcast: 'إنشاء بث',
    sendBroadcastsSub: 'إرسال البثوث وإدارة قوالب الإشعارات',
    title: 'العنوان',
    targetAudience: 'الجمهور المستهدف',
    notificationChannels: 'قنوات الإشعار',
    sendTime: 'وقت الإرسال',
    sendNow: 'إرسال الآن',
    scheduleSend: 'جدولة',
    preview: 'معاينة',
    recentBroadcasts: 'البثوث الأخيرة',
    notificationPreview: 'معاينة الإشعار',
    templateName: 'اسم القالب',
    type: 'النوع',
    content: 'المحتوى',
    allUsersAudience: 'جميع المستخدمين',
    studentsOnly: 'الطلاب فقط',
    instructorsOnly: 'المحاضرون فقط',
    adminsOnly: 'المديرون فقط',
    // Feedback & Support
    openTickets: 'التذاكر المفتوحة',
    avgResponseTime: 'متوسط وقت الاستجابة',
    satisfactionRate: 'معدل الرضا',
    ticketId: 'رقم التذكرة',
    assignedTo: 'مسند إلى',
    respondToTicket: 'الرد',
    closeTicket: 'إغلاق التذكرة',
    escalateTicket: 'تصعيد',
    totalTickets: 'إجمالي التذاكر',
    manageFeedbackSub: 'إدارة ملاحظات المستخدمين والتقارير وتذاكر الدعم',
    searchTickets: 'البحث عن التذاكر...',
    allPriorities: 'جميع الأولويات',
    updateStatus: 'تحديث الحالة',
    reply: 'الرد',
    sendReply: 'إرسال الرد',
    // System Configuration
    generalSettings: 'الإعدادات العامة',
    securitySettings: 'إعدادات الأمان',
    emailSettings: 'إعدادات البريد',
    backupSettings: 'إعدادات النسخ الاحتياطي',
    platformName: 'اسم المنصة',
    platformUrl: 'رابط المنصة',
    maintenanceMode: 'وضع الصيانة',
    autoBackup: 'نسخ احتياطي تلقائي',
    backupFrequency: 'تكرار النسخ الاحتياطي',
    smtpServer: 'خادم SMTP',
    enableTwoFactor: 'التحقق بخطوتين',
    passwordPolicy: 'سياسة كلمة المرور',
    manageSystemSub: 'إدارة إعدادات النظام والتكاملات وسجلات المراجعة',
    featureToggles: 'مفاتيح الميزات',
    pointsConfiguration: 'إعدادات النقاط',
    badgesLabel: 'الشارات',
    saveChanges: 'حفظ التغييرات',
    searchLogs: 'البحث في السجلات...',
    allActions: 'جميع الإجراءات',
    userActionsFilter: 'إجراءات المستخدمين',
    courseActionsFilter: 'إجراءات المقررات',
    systemActionsFilter: 'إجراءات النظام',
    exportLogs: 'تصدير السجلات',
    timestamp: 'الطابع الزمني',
    action: 'الإجراء',
    user: 'المستخدم',
    target: 'الهدف',
    ipAddress: 'عنوان IP',
    lastSync: 'آخر مزامنة',
    syncFrequencyLabel: 'تكرار المزامنة',
    dataTypes: 'أنواع البيانات',
    syncNow: 'مزامنة الآن',
    notConnected: 'غير متصل',
    configureConnection: 'تكوين الاتصال',
    awardPointsDesc: 'منح النقاط للأنشطة المختلفة',
    enableBadgesDesc: 'تفعيل شارات الإنجاز للطلاب',
    showLeaderboardsDesc: 'عرض لوحات الصدارة العامة',
    // Schedule Management
    scheduleManagement: 'إدارة الجداول',
    manageScheduleSub: 'إنشاء وإدارة جداول المحاضرات لقسمك',
    addSchedule: 'إضافة جدول',
    editSchedule: 'تعديل جدول',
    deleteSchedule: 'حذف جدول',
    day: 'اليوم',
    startTime: 'وقت البداية',
    endTime: 'وقت النهاية',
    room: 'القاعة',
    scheduleType: 'النوع',
    lecture: 'محاضرة',
    lab: 'معمل',
    section: 'سكشن',
    tutorial: 'تدريب',
    sunday: 'الأحد',
    monday: 'الإثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    saturday: 'السبت',
    conflictWarning: 'تم اكتشاف تعارض في الجدول!',
    noSchedules: 'لم يتم إنشاء جداول بعد',
    weeklyView: 'العرض الأسبوعي',
    totalSessions: 'إجمالي الحصص',
    totalRooms: 'القاعات المستخدمة',
    searchSchedules: 'البحث في الجداول...',
    allDays: 'جميع الأيام',
    allTypes: 'جميع الأنواع',
    // Exam Schedule
    examSchedule: 'جدول الامتحانات',
    manageExamsSub: 'جدولة وإدارة الامتحانات لمقررات قسمك',
    addExam: 'إضافة امتحان',
    editExam: 'تعديل امتحان',
    deleteExam: 'حذف امتحان',
    examType: 'نوع الامتحان',
    midterm: 'نصفي',
    final: 'نهائي',
    quiz: 'اختبار قصير',
    practical: 'عملي',
    duration: 'المدة (دقيقة)',
    examDate: 'تاريخ الامتحان',
    noExams: 'لم يتم جدولة امتحانات بعد',
    searchExams: 'البحث في الامتحانات...',
    allExamTypes: 'جميع أنواع الامتحانات',
    totalExams: 'إجمالي الامتحانات',
    upcomingExams: 'الامتحانات القادمة',
    // Enrollment Periods
    enrollmentPeriods: 'فترات التسجيل',
    manageEnrollmentSub: 'فتح وإدارة فترات التسجيل لمقررات قسمك',
    addEnrollmentPeriod: 'إضافة فترة',
    editEnrollmentPeriod: 'تعديل فترة',
    deleteEnrollmentPeriod: 'حذف فترة',
    waitlist: 'قائمة الانتظار',
    waitlistCapacity: 'سعة قائمة الانتظار',
    waitlistEnabled: 'تفعيل قائمة الانتظار',
    enrollmentStatus: 'الحالة',
    activePeriod: 'نشطة',
    closedPeriod: 'مغلقة',
    upcomingPeriod: 'قادمة',
    noEnrollmentPeriods: 'لم يتم إنشاء فترات تسجيل بعد',
    searchEnrollment: 'البحث في فترات التسجيل...',
    totalPeriods: 'إجمالي الفترات',
    activePeriods: 'الفترات النشطة',
    openEnrollmentPeriod: 'فتح فترة',
    // Prerequisites Management
    prerequisitesManagement: 'المتطلبات السابقة',
    managePrereqSub: 'تعيين وإدارة المتطلبات السابقة لمقررات قسمك',
    addPrerequisite: 'إضافة متطلب',
    removePrerequisite: 'إزالة',
    prerequisitesFor: 'المتطلبات السابقة لـ',
    noPrerequisites: 'لا توجد متطلبات سابقة',
    availableCourses: 'المقررات المتاحة',
    currentPrerequisites: 'المتطلبات الحالية',
    prerequisiteChain: 'سلسلة المتطلبات',
    searchPrerequisites: 'البحث عن المقررات...',
    selectCourse: 'اختر المقرر',
    selectInstructor: 'اختر المحاضر',
    selectTA: 'اختر المعيد',
    assignedTAs: 'المعيدون المعينون',
    assignInstructor: 'تعيين محاضر',
    assignTA: 'تعيين معيد',
    departmentScope: 'نطاق القسم',
    yourDepartment: 'قسمك',
    courseAdded: 'تم إنشاء المقرر بنجاح',
    courseUpdated: 'تم تحديث المقرر بنجاح',
    courseDeleted: 'تم حذف المقرر بنجاح',
    staffAssignment: 'تعيين الموظفين',
    assign: 'تعيين',
    staffAssignmentTab: 'تعيين الموظفين',
    scheduleTab: 'الجدول الدراسي',
    examsTab: 'جدول الامتحانات',
    coursesTab: 'المقررات',
    unassigned: 'غير معين',
    none: 'لا يوجد',
    classSchedule: 'جدول المحاضرات',
    examScheduleTitle: 'جدول الامتحانات',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('eduverse-language');
      return (saved as Language) || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('eduverse-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
