import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    search: 'Search...',
    searchPlaceholder: 'Search users, courses, departments...',
    notifications: 'Notifications',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    viewProfile: 'View Profile',
    logout: 'Logout',
    dashboard: 'Dashboard',
    adminDashboard: 'Admin Dashboard',
    userManagement: 'User Management',
    courseManagement: 'Course Management',
    departmentManagement: 'Department Management',
    academicCalendar: 'Academic Calendar',
    analytics: 'Analytics & Reports',
    communication: 'Communication',
    feedback: 'Feedback & Support',
    systemConfig: 'System Configuration',
    settings: 'Settings',
    welcomeBack: 'Welcome back',
    overviewDescription: 'Manage your platform, monitor system health, and configure settings.',
    systemHealth: 'System Health',
    platformStatus: 'Platform Status',
    totalUsers: 'Total Users',
    activeUsers: 'Active Users',
    totalCourses: 'Total Courses',
    activeCourses: 'Active Courses',
    totalDepartments: 'Departments',
    systemUptime: 'System Uptime',
    pendingRequests: 'Pending Requests',
    users: 'Users',
    addUser: 'Add User',
    editUser: 'Edit User',
    deleteUser: 'Delete User',
    userName: 'User Name',
    email: 'Email',
    role: 'Role',
    status: 'Status',
    lastActive: 'Last Active',
    student: 'Student',
    instructor: 'Instructor',
    ta: 'Teaching Assistant',
    admin: 'Admin',
    active: 'Active',
    inactive: 'Inactive',
    suspended: 'Suspended',
    assignRole: 'Assign Role',
    permissions: 'Permissions',
    courses: 'Courses',
    addCourse: 'Add Course',
    editCourse: 'Edit Course',
    deleteCourse: 'Delete Course',
    courseCode: 'Course Code',
    courseName: 'Course Name',
    department: 'Department',
    semester: 'Semester',
    credits: 'Credits',
    enrolled: 'Enrolled',
    capacity: 'Capacity',
    departments: 'Departments',
    addDepartment: 'Add Department',
    editDepartment: 'Edit Department',
    deleteDepartment: 'Delete Department',
    departmentName: 'Department Name',
    faculty: 'Faculty',
    headOfDepartment: 'Head of Department',
    coursesCount: 'Courses Count',
    studentsCount: 'Students Count',
    instructorsCount: 'Instructors Count',
    calendar: 'Calendar',
    addEvent: 'Add Event',
    editEvent: 'Edit Event',
    deleteEvent: 'Delete Event',
    eventTitle: 'Event Title',
    eventDate: 'Event Date',
    eventType: 'Event Type',
    holiday: 'Holiday',
    examPeriod: 'Exam Period',
    semesterStart: 'Semester Start',
    semesterEnd: 'Semester End',
    registrationPeriod: 'Registration Period',
    systemAnalytics: 'System Analytics',
    userStatistics: 'User Statistics',
    courseStatistics: 'Course Statistics',
    engagementMetrics: 'Engagement Metrics',
    aiUsageStats: 'AI Feature Usage',
    exportData: 'Export Data',
    exportPDF: 'Export PDF',
    exportExcel: 'Export Excel',
    generateReport: 'Generate Report',
    broadcastNotification: 'Broadcast Notification',
    sendToAll: 'Send to All Users',
    sendToStudents: 'Send to Students',
    sendToInstructors: 'Send to Instructors',
    notificationTemplates: 'Notification Templates',
    createTemplate: 'Create Template',
    editTemplate: 'Edit Template',
    userFeedback: 'User Feedback',
    supportTickets: 'Support Tickets',
    resolved: 'Resolved',
    pending: 'Pending',
    inProgress: 'In Progress',
    priority: 'Priority',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    auditLogs: 'Audit Logs',
    gamificationSettings: 'Gamification Settings',
    apiIntegrations: 'API Integrations',
    enablePoints: 'Enable Points System',
    enableBadges: 'Enable Badges',
    enableLeaderboards: 'Enable Leaderboards',
    moodleIntegration: 'Moodle Integration',
    blackboardIntegration: 'Blackboard Integration',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    submit: 'Submit',
    apply: 'Apply',
    reset: 'Reset',
    filter: 'Filter',
    sort: 'Sort',
    noData: 'No data available',
    viewAll: 'View All',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    download: 'Download',
    upload: 'Upload',
    export: 'Export',
    import: 'Import',
    refresh: 'Refresh',
    date: 'Date',
    time: 'Time',
    actions: 'Actions',
    more: 'More',
  },
  ar: {
    search: 'بحث...',
    searchPlaceholder: 'البحث عن المستخدمين والمقررات والأقسام...',
    notifications: 'الإشعارات',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    viewProfile: 'عرض الملف الشخصي',
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    adminDashboard: 'لوحة تحكم المدير',
    userManagement: 'إدارة المستخدمين',
    courseManagement: 'إدارة المقررات',
    departmentManagement: 'إدارة الأقسام',
    academicCalendar: 'التقويم الأكاديمي',
    analytics: 'التحليلات والتقارير',
    communication: 'التواصل',
    feedback: 'الملاحظات والدعم',
    systemConfig: 'إعدادات النظام',
    settings: 'الإعدادات',
    welcomeBack: 'مرحباً بعودتك',
    overviewDescription: 'إدارة المنصة ومراقبة صحة النظام وتكوين الإعدادات.',
    systemHealth: 'صحة النظام',
    platformStatus: 'حالة المنصة',
    totalUsers: 'إجمالي المستخدمين',
    activeUsers: 'المستخدمون النشطون',
    totalCourses: 'إجمالي المقررات',
    activeCourses: 'المقررات النشطة',
    totalDepartments: 'الأقسام',
    systemUptime: 'وقت تشغيل النظام',
    pendingRequests: 'الطلبات المعلقة',
    users: 'المستخدمون',
    addUser: 'إضافة مستخدم',
    editUser: 'تعديل مستخدم',
    deleteUser: 'حذف مستخدم',
    userName: 'اسم المستخدم',
    email: 'البريد الإلكتروني',
    role: 'الدور',
    status: 'الحالة',
    lastActive: 'آخر نشاط',
    student: 'طالب',
    instructor: 'محاضر',
    ta: 'معيد',
    admin: 'مدير',
    active: 'نشط',
    inactive: 'غير نشط',
    suspended: 'معلق',
    assignRole: 'تعيين دور',
    permissions: 'الصلاحيات',
    courses: 'المقررات',
    addCourse: 'إضافة مقرر',
    editCourse: 'تعديل مقرر',
    deleteCourse: 'حذف مقرر',
    courseCode: 'رمز المقرر',
    courseName: 'اسم المقرر',
    department: 'القسم',
    semester: 'الفصل الدراسي',
    credits: 'الساعات المعتمدة',
    enrolled: 'المسجلين',
    capacity: 'السعة',
    departments: 'الأقسام',
    addDepartment: 'إضافة قسم',
    editDepartment: 'تعديل قسم',
    deleteDepartment: 'حذف قسم',
    departmentName: 'اسم القسم',
    faculty: 'الكلية',
    headOfDepartment: 'رئيس القسم',
    coursesCount: 'عدد المقررات',
    studentsCount: 'عدد الطلاب',
    instructorsCount: 'عدد المحاضرين',
    calendar: 'التقويم',
    addEvent: 'إضافة حدث',
    editEvent: 'تعديل حدث',
    deleteEvent: 'حذف حدث',
    eventTitle: 'عنوان الحدث',
    eventDate: 'تاريخ الحدث',
    eventType: 'نوع الحدث',
    holiday: 'عطلة',
    examPeriod: 'فترة الامتحانات',
    semesterStart: 'بداية الفصل',
    semesterEnd: 'نهاية الفصل',
    registrationPeriod: 'فترة التسجيل',
    systemAnalytics: 'تحليلات النظام',
    userStatistics: 'إحصائيات المستخدمين',
    courseStatistics: 'إحصائيات المقررات',
    engagementMetrics: 'مقاييس المشاركة',
    aiUsageStats: 'استخدام ميزات الذكاء الاصطناعي',
    exportData: 'تصدير البيانات',
    exportPDF: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    generateReport: 'إنشاء تقرير',
    broadcastNotification: 'إشعار عام',
    sendToAll: 'إرسال للجميع',
    sendToStudents: 'إرسال للطلاب',
    sendToInstructors: 'إرسال للمحاضرين',
    notificationTemplates: 'قوالب الإشعارات',
    createTemplate: 'إنشاء قالب',
    editTemplate: 'تعديل قالب',
    userFeedback: 'ملاحظات المستخدمين',
    supportTickets: 'تذاكر الدعم',
    resolved: 'تم الحل',
    pending: 'معلق',
    inProgress: 'قيد المعالجة',
    priority: 'الأولوية',
    high: 'عالية',
    medium: 'متوسطة',
    low: 'منخفضة',
    auditLogs: 'سجلات المراجعة',
    gamificationSettings: 'إعدادات اللعبة',
    apiIntegrations: 'تكاملات API',
    enablePoints: 'تفعيل نظام النقاط',
    enableBadges: 'تفعيل الشارات',
    enableLeaderboards: 'تفعيل لوحات الصدارة',
    moodleIntegration: 'تكامل Moodle',
    blackboardIntegration: 'تكامل Blackboard',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجاح',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    close: 'إغلاق',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    submit: 'إرسال',
    apply: 'تطبيق',
    reset: 'إعادة تعيين',
    filter: 'تصفية',
    sort: 'ترتيب',
    noData: 'لا توجد بيانات',
    viewAll: 'عرض الكل',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    download: 'تنزيل',
    upload: 'رفع',
    export: 'تصدير',
    import: 'استيراد',
    refresh: 'تحديث',
    date: 'التاريخ',
    time: 'الوقت',
    actions: 'الإجراءات',
    more: 'المزيد',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('eduverse-admin-language');
      return (saved as Language) || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('eduverse-admin-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
